CREATE TABLE change_request_approval
(
    id                          NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    change_request_id           NUMBER(38, 0),
    change_request_role_user_id NUMBER(38, 0),
    overall_status              VARCHAR2(100),
    created_date                TIMESTAMP,
    created_by                  VARCHAR2(100),
    modified_date               TIMESTAMP,
    modified_by                 VARCHAR2(100),
    CONSTRAINT pk_change_request_approval PRIMARY KEY (id)
);