CREATE SEQUENCE CHANGE_FLOW_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE CHANGE_FLOW
(
    ID            NUMBER(38, 0) NOT NULL,
    NAME          VARCHAR2(255),
    DESCRIPTION   VARCHAR2(1000),
    FLOW_DATA     CLOB,
    CREATED_DATE  TIMESTAMP,
    CREATED_BY    VARCHAR2(100),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY   VARCHAR2(100),
    DELETED       NUMBER(1) DEFAULT 0,
    DELETED_BY    VARCHAR2(100),
    FLOW_NODES    CLOB,
    FLOW_EDGES    CLOB,
    DELETED_DATE  TIMESTAMP,
    CONSTRAINT PK_CHANGE_FLOW PRIMARY KEY (ID)
);