package com.example.demo.service.impl;

import com.example.demo.entity.ChangeRequestEntity;
import com.example.demo.enums.ApprovalResultStatus;
import com.example.demo.enums.FlowConstants;
import com.example.demo.enums.NodeType;
import com.example.demo.mapper.ChangeRequestMapper;
import com.example.demo.model.*;
import com.example.demo.repository.ChangeRequestRepository;
import com.example.demo.service.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.*;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
/**
 * Generated by K-tool
 * Created date: 2025-06-30
 */
class ChangeRequestServiceImplTest {

    @Mock
    private ChangeRequestRepository changeRequestRepository;
    @Mock
    private ChangeRequestMapper changeRequestMapper;
    @Mock
    private FlowManagementService flowManagementService;
    @Mock
    private ChangeTemplateService changeTemplateService;
    @Mock
    private ChangeRequestApprovalService changeRequestApprovalService;
    @Mock
    private ChangeRequestRoleService changeRequestRoleService;
    @Mock
    private ChangeRequestHistoryService changeRequestHistoryService;
    @Mock
    private ChangeStatusService changeStatusService;
    @Mock
    private ChangeFlowService changeFlowService;
    @InjectMocks
    private ChangeRequestServiceImpl changeRequestService;

    @BeforeEach
    void setUp() {
    }

    @Test
    void findById_positiveTest() throws BusinessException {
        // [EN] Input: changeRequestId = 1L, changeRequestRepository.findById(1L) returns a ChangeRequestEntity
        // [EN] Expected: Returns a ChangeRequestModel mapped from the ChangeRequestEntity
        Long changeRequestId = 1L;
        ChangeRequestEntity changeRequestEntity = new ChangeRequestEntity();
        changeRequestEntity.setId(changeRequestId);
        ChangeRequestModel changeRequestModel = new ChangeRequestModel();
        changeRequestModel.setId(changeRequestId);

        when(changeRequestRepository.findById(changeRequestId)).thenReturn(
                Optional.of(changeRequestEntity));
        when(changeRequestMapper.toDto(changeRequestEntity)).thenReturn(changeRequestModel);

        ChangeRequestModel result = changeRequestService.findById(changeRequestId);

        assertThat(result).isEqualTo(changeRequestModel);
        verify(changeRequestRepository).findById(changeRequestId);
        verify(changeRequestMapper).toDto(changeRequestEntity);
    }

    @Test
    void findById_negativeTest_nullId() {
        // [EN] Input: changeRequestId = null
        // [EN] Expected: Throws BusinessException with CHANGE_REQUEST_ID_REQUIRED error code
        BusinessException exception =
                assertThrows(BusinessException.class, () -> changeRequestService.findById(null));
        assertThat(exception.getMessage()).isEqualTo(
                ErrorCodeCommon.CHANGE_REQUEST_ID_REQUIRED.getMessage());
    }

    @Test
    void findById_negativeTest_notFound() {
        // [EN] Input: changeRequestId = 1L, changeRequestRepository.findById(1L) returns Optional.empty()
        // [EN] Expected: Throws BusinessException with CHANGE_REQUEST_ID_NOT_FOUND error code
        Long changeRequestId = 1L;
        when(changeRequestRepository.findById(changeRequestId)).thenReturn(Optional.empty());
        BusinessException exception = assertThrows(BusinessException.class,
                () -> changeRequestService.findById(changeRequestId));
        assertThat(exception.getMessage()).isEqualTo(
                String.format(ErrorCodeCommon.CHANGE_REQUEST_ID_NOT_FOUND.getMessage(),
                        changeRequestId));
        verify(changeRequestRepository).findById(changeRequestId);
    }

    @Test
    void processApprovalReply_positiveTest() {
        // [EN] Input: replyModel with valid data, mocks return expected values
        // [EN] Expected: Returns the input replyModel, verifies interactions with mocks

        ChangeRequestApprovalResultModel replyModel = new ChangeRequestApprovalResultModel();
        replyModel.setChangeRequestApprovalId(1L);
        replyModel.setStatus(ApprovalResultStatus.ACCEPT);

        ChangeRequestApprovalModel approvalModel = new ChangeRequestApprovalModel();
        approvalModel.setId(1L);
        approvalModel.setChangeRequestId(1L);

        ChangeRequestEntity changeRequestEntity = new ChangeRequestEntity();
        changeRequestEntity.setId(1L);
        changeRequestEntity.setChangeTemplateId(1L);
        changeRequestEntity.setChangeFlowNodeStrId("node1");

        ChangeTemplateModel changeTemplateModel = new ChangeTemplateModel();
        changeTemplateModel.setId(1L);
        changeTemplateModel.setChangeFlowId(1L);

        IndexedChangeFlowDataModel flowDataModel = new IndexedChangeFlowDataModel();
        Map<String, FlowEdgeModel> indexedEdges = new HashMap<>();
        FlowEdgeModel edgeModel = new FlowEdgeModel();
        edgeModel.setChangeFlowId(1L);
        flowDataModel.setIndexedEdges(indexedEdges);

        FlowTransitionDetail flowTransitionDetail =
                FlowTransitionDetail.builder().changeRequest(changeRequestEntity).changeFlowId(1L)
                        .currentChangeFlowNodeHandleId("node1_APPROVED").build();

        when(changeRequestApprovalService.findById(1L)).thenReturn(approvalModel);
        when(changeRequestRepository.findById(1L)).thenReturn(Optional.of(changeRequestEntity));
        when(changeTemplateService.findById(1L)).thenReturn(changeTemplateModel);
        when(changeFlowService.findById(1L)).thenReturn(Optional.of(new ChangeFlowModel()));
        when(flowManagementService.createApprovalNodeHandleIdFromNodeIdAndStatus("node1",
                ApprovalResultStatus.ACCEPT)).thenReturn("node1_APPROVED");

        when(flowManagementService.getFlowDataByChangeFlowId(1L)).thenReturn(flowDataModel);
        when(flowManagementService.getOrDefaultEdgeByNodeHandleId(1L, "node1_APPROVED",
                indexedEdges)).thenReturn(edgeModel);

        ChangeRequestApprovalResultModel result =
                changeRequestService.processApprovalReply(replyModel);

        assertThat(result).isEqualTo(replyModel);
        verify(changeRequestApprovalService).findById(1L);
        verify(changeRequestRepository).findById(1L);
        verify(changeTemplateService).findById(1L);
        verify(changeFlowService).findById(1L);
        verify(flowManagementService).getFlowDataByChangeFlowId(1L);
        verify(flowManagementService).getOrDefaultEdgeByNodeHandleId(1L, "node1_APPROVED",
                indexedEdges);
    }

    @Test
    void processApprovalReply_negativeTest_nullReplyModel() {
        // [EN] Input: replyModel = null
        // [EN] Expected: Throws BusinessException with CHANGE_REQUEST_APPROVAL_INPUT_REQUIRED error code
        BusinessException exception = assertThrows(BusinessException.class,
                () -> changeRequestService.processApprovalReply(null));
        assertThat(exception.getMessage()).isEqualTo(
                ErrorCodeCommon.CHANGE_REQUEST_APPROVAL_INPUT_REQUIRED.getMessage());
    }

    @Test
    void processApprovalReply_negativeTest_nullStatus() {
        // [EN] Input: replyModel with null status
        // [EN] Expected: Throws BusinessException with CHANGE_REQUEST_APPROVAL_INPUT_REQUIRED error code
        ChangeRequestApprovalResultModel replyModel = new ChangeRequestApprovalResultModel();
        replyModel.setChangeRequestApprovalId(1L);
        replyModel.setStatus(null);
        BusinessException exception = assertThrows(BusinessException.class,
                () -> changeRequestService.processApprovalReply(replyModel));
        assertThat(exception.getMessage()).isEqualTo(
                ErrorCodeCommon.CHANGE_REQUEST_APPROVAL_INPUT_REQUIRED.getMessage());
    }

    @Test
    void processApprovalReply_negativeTest_nullApprovalId() {
        // [EN] Input: replyModel with null approvalId
        // [EN] Expected: Throws BusinessException with CHANGE_REQUEST_APPROVAL_ID_REQUIRED error code
        ChangeRequestApprovalResultModel replyModel = new ChangeRequestApprovalResultModel();
        replyModel.setChangeRequestApprovalId(null);
        replyModel.setStatus(ApprovalResultStatus.ACCEPT);
        BusinessException exception = assertThrows(BusinessException.class,
                () -> changeRequestService.processApprovalReply(replyModel));
        assertThat(exception.getMessage()).isEqualTo(
                ErrorCodeCommon.CHANGE_REQUEST_APPROVAL_ID_REQUIRED.getMessage());
    }

    @Test
    void processApprovalReply_negativeTest_approvalNotFound() {
        // [EN] Input: replyModel with approvalId 1L, changeRequestApprovalService.findById(1L) returns null
        // [EN] Expected: Throws BusinessException with CHANGE_REQUEST_APPROVAL_NOT_FOUND error code
        ChangeRequestApprovalResultModel replyModel = new ChangeRequestApprovalResultModel();
        replyModel.setChangeRequestApprovalId(1L);
        replyModel.setStatus(ApprovalResultStatus.ACCEPT);
        when(changeRequestApprovalService.findById(1L)).thenReturn(null);
        BusinessException exception = assertThrows(BusinessException.class,
                () -> changeRequestService.processApprovalReply(replyModel));
        assertThat(exception.getMessage()).isEqualTo(
                String.format(ErrorCodeCommon.CHANGE_REQUEST_APPROVAL_NOT_FOUND.getMessage(), 1L));
        verify(changeRequestApprovalService).findById(1L);
    }

    @Test
    void processApprovalReply_negativeTest_requestIdNull() {
        // [EN] Input: replyModel with approvalId 1L, changeRequestApprovalService.findById(1L) returns an approvalModel with null changeRequestId
        // [EN] Expected: Throws BusinessException with CHANGE_REQUEST_APPROVAL_REQUEST_ID_NULL error code
        ChangeRequestApprovalResultModel replyModel = new ChangeRequestApprovalResultModel();
        replyModel.setChangeRequestApprovalId(1L);
        replyModel.setStatus(ApprovalResultStatus.ACCEPT);
        ChangeRequestApprovalModel approvalModel = new ChangeRequestApprovalModel();
        approvalModel.setId(1L);
        approvalModel.setChangeRequestId(null);
        when(changeRequestApprovalService.findById(1L)).thenReturn(approvalModel);
        BusinessException exception = assertThrows(BusinessException.class,
                () -> changeRequestService.processApprovalReply(replyModel));
        assertThat(exception.getMessage()).isEqualTo(
                String.format(ErrorCodeCommon.CHANGE_REQUEST_APPROVAL_REQUEST_ID_NULL.getMessage(),
                        1L));
        verify(changeRequestApprovalService).findById(1L);
    }

    @Test
    void processApprovalReply_negativeTest_changeRequestNotFound() {
        // [EN] Input: replyModel with valid data, changeRequestRepository.findById(1L) returns Optional.empty()
        // [EN] Expected: Throws BusinessException with CHANGE_REQUEST_ID_NOT_FOUND error code
        ChangeRequestApprovalResultModel replyModel = new ChangeRequestApprovalResultModel();
        replyModel.setChangeRequestApprovalId(1L);
        replyModel.setStatus(ApprovalResultStatus.ACCEPT);
        ChangeRequestApprovalModel approvalModel = new ChangeRequestApprovalModel();
        approvalModel.setId(1L);
        approvalModel.setChangeRequestId(1L);
        when(changeRequestApprovalService.findById(1L)).thenReturn(approvalModel);
        when(changeRequestRepository.findById(1L)).thenReturn(Optional.empty());
        BusinessException exception = assertThrows(BusinessException.class,
                () -> changeRequestService.processApprovalReply(replyModel));
        assertThat(exception.getMessage()).isEqualTo(
                String.format(ErrorCodeCommon.CHANGE_REQUEST_ID_NOT_FOUND.getMessage(), 1L));
        verify(changeRequestApprovalService).findById(1L);
        verify(changeRequestRepository).findById(1L);
    }

    @Test
    void processApprovalReply_negativeTest_changeTemplateIdMissing() {
        // [EN] Input: replyModel with valid data, changeRequestEntity has null changeTemplateId
        // [EN] Expected: Throws BusinessException with CHANGE_TEMPLATE_ID_MISSING error code
        ChangeRequestApprovalResultModel replyModel = new ChangeRequestApprovalResultModel();
        replyModel.setChangeRequestApprovalId(1L);
        replyModel.setStatus(ApprovalResultStatus.ACCEPT);
        ChangeRequestApprovalModel approvalModel = new ChangeRequestApprovalModel();
        approvalModel.setId(1L);
        approvalModel.setChangeRequestId(1L);
        ChangeRequestEntity changeRequestEntity = new ChangeRequestEntity();
        changeRequestEntity.setId(1L);
        changeRequestEntity.setChangeTemplateId(null);
        when(changeRequestApprovalService.findById(1L)).thenReturn(approvalModel);
        when(changeRequestRepository.findById(1L)).thenReturn(Optional.of(changeRequestEntity));
        BusinessException exception = assertThrows(BusinessException.class,
                () -> changeRequestService.processApprovalReply(replyModel));
        assertThat(exception.getMessage()).isEqualTo(
                String.format(ErrorCodeCommon.CHANGE_TEMPLATE_ID_MISSING.getMessage(), null));
        verify(changeRequestApprovalService).findById(1L);
        verify(changeRequestRepository).findById(1L);
    }

    @Test
    void processApprovalReply_negativeTest_changeTemplateNotFound() {
        // [EN] Input: replyModel with valid data, changeTemplateService.findById(1L) returns null
        // [EN] Expected: Throws BusinessException with CHANGE_TEMPLATE_NOT_FOUND error code
        ChangeRequestApprovalResultModel replyModel = new ChangeRequestApprovalResultModel();
        replyModel.setChangeRequestApprovalId(1L);
        replyModel.setStatus(ApprovalResultStatus.ACCEPT);
        ChangeRequestApprovalModel approvalModel = new ChangeRequestApprovalModel();
        approvalModel.setId(1L);
        approvalModel.setChangeRequestId(1L);
        ChangeRequestEntity changeRequestEntity = new ChangeRequestEntity();
        changeRequestEntity.setId(1L);
        changeRequestEntity.setChangeTemplateId(1L);
        when(changeRequestApprovalService.findById(1L)).thenReturn(approvalModel);
        when(changeRequestRepository.findById(1L)).thenReturn(Optional.of(changeRequestEntity));
        when(changeTemplateService.findById(1L)).thenReturn(null);
        BusinessException exception = assertThrows(BusinessException.class,
                () -> changeRequestService.processApprovalReply(replyModel));
        assertThat(exception.getMessage()).isEqualTo(
                String.format(ErrorCodeCommon.CHANGE_TEMPLATE_NOT_FOUND.getMessage(), 1L));
        verify(changeRequestApprovalService).findById(1L);
        verify(changeRequestRepository).findById(1L);
        verify(changeTemplateService).findById(1L);
    }

    @Test
    void processApprovalReply_negativeTest_changeFlowConfigurationError() {
        // [EN] Input: replyModel with valid data, changeTemplateModel has null changeFlowId
        // [EN] Expected: Throws BusinessException with CHANGE_FLOW_CONFIGURATION_ERROR error code
        ChangeRequestApprovalResultModel replyModel = new ChangeRequestApprovalResultModel();
        replyModel.setChangeRequestApprovalId(1L);
        replyModel.setStatus(ApprovalResultStatus.ACCEPT);
        ChangeRequestApprovalModel approvalModel = new ChangeRequestApprovalModel();
        approvalModel.setId(1L);
        approvalModel.setChangeRequestId(1L);
        ChangeRequestEntity changeRequestEntity = new ChangeRequestEntity();
        changeRequestEntity.setId(1L);
        changeRequestEntity.setChangeTemplateId(1L);
        ChangeTemplateModel changeTemplateModel = new ChangeTemplateModel();
        changeTemplateModel.setId(1L);
        changeTemplateModel.setChangeFlowId(null);
        when(changeRequestApprovalService.findById(1L)).thenReturn(approvalModel);
        when(changeRequestRepository.findById(1L)).thenReturn(Optional.of(changeRequestEntity));
        when(changeTemplateService.findById(1L)).thenReturn(changeTemplateModel);
        BusinessException exception = assertThrows(BusinessException.class,
                () -> changeRequestService.processApprovalReply(replyModel));
        assertThat(exception.getMessage()).isEqualTo(
                String.format(ErrorCodeCommon.CHANGE_FLOW_CONFIGURATION_ERROR.getMessage(), null));
        verify(changeRequestApprovalService).findById(1L);
        verify(changeRequestRepository).findById(1L);
        verify(changeTemplateService).findById(1L);
    }

    @Test
    void processApprovalReply_negativeTest_changeFlowNotFound() {
        // [EN] Input: replyModel with valid data, changeFlowService.findById(1L) returns Optional.empty()
        // [EN] Expected: Throws BusinessException with CHANGE_FLOW_NOT_FOUND error code
        ChangeRequestApprovalResultModel replyModel = new ChangeRequestApprovalResultModel();
        replyModel.setChangeRequestApprovalId(1L);
        replyModel.setStatus(ApprovalResultStatus.ACCEPT);
        ChangeRequestApprovalModel approvalModel = new ChangeRequestApprovalModel();
        approvalModel.setId(1L);
        approvalModel.setChangeRequestId(1L);
        ChangeRequestEntity changeRequestEntity = new ChangeRequestEntity();
        changeRequestEntity.setId(1L);
        changeRequestEntity.setChangeTemplateId(1L);
        ChangeTemplateModel changeTemplateModel = new ChangeTemplateModel();
        changeTemplateModel.setId(1L);
        changeTemplateModel.setChangeFlowId(1L);
        when(changeRequestApprovalService.findById(1L)).thenReturn(approvalModel);
        when(changeRequestRepository.findById(1L)).thenReturn(Optional.of(changeRequestEntity));
        when(changeTemplateService.findById(1L)).thenReturn(changeTemplateModel);
        when(changeFlowService.findById(1L)).thenReturn(Optional.empty());
        BusinessException exception = assertThrows(BusinessException.class,
                () -> changeRequestService.processApprovalReply(replyModel));
        assertThat(exception.getMessage()).isEqualTo(
                String.format(ErrorCodeCommon.CHANGE_FLOW_NOT_FOUND.getMessage(), 1L));
        verify(changeRequestApprovalService).findById(1L);
        verify(changeRequestRepository).findById(1L);
        verify(changeTemplateService).findById(1L);
        verify(changeFlowService).findById(1L);
    }

    @Test
    void validateAndPrepareChangeCoordinatorTransition_positiveTest() {
        // [EN] Input: changeRequestId = 1L, nextChangeStatusId = 2L, mocks return valid data
        // [EN] Expected: Returns a FlowTransitionDetail object with correct data

        Long changeRequestId = 1L;
        Long nextChangeStatusId = 2L;

        ChangeRequestEntity changeRequestEntity = new ChangeRequestEntity();
        changeRequestEntity.setId(changeRequestId);
        changeRequestEntity.setChangeTemplateId(1L);
        changeRequestEntity.setChangeStatusId(1L);

        ChangeTemplateModel changeTemplateModel = new ChangeTemplateModel();
        changeTemplateModel.setId(1L);
        changeTemplateModel.setChangeFlowId(1L);

        List<ChangeStatusModel> remainingStatusesInSameStage = new ArrayList<>();
        ChangeStatusModel nextStatus = new ChangeStatusModel();
        nextStatus.setId(nextChangeStatusId);
        remainingStatusesInSameStage.add(nextStatus);

        when(changeRequestRepository.findById(changeRequestId)).thenReturn(
                Optional.of(changeRequestEntity));
        when(changeTemplateService.findById(1L)).thenReturn(changeTemplateModel);
        when(changeStatusService.findRemainingStatusesInSameStage(1L)).thenReturn(
                remainingStatusesInSameStage);

        FlowTransitionDetail result =
                changeRequestService.validateAndPrepareChangeCoordinatorTransition(changeRequestId,
                        nextChangeStatusId);

        assertThat(result.getChangeFlowId()).isEqualTo(1L);
        assertThat(result.getChangeRequest()).isEqualTo(changeRequestEntity);
        assertThat(result.getCurrentChangeFlowNodeHandleId()).isEqualTo(
                "1" + FlowConstants.HANDLE_SEPARATOR + FlowConstants.OUTPUT_KEYWORD);
        verify(changeRequestRepository).findById(changeRequestId);
        verify(changeTemplateService).findById(1L);
        verify(changeStatusService).findRemainingStatusesInSameStage(1L);
    }

    @Test
    void validateAndPrepareChangeCoordinatorTransition_negativeTest_nullChangeRequestId() {
        // [EN] Input: changeRequestId = null, nextChangeStatusId = 2L
        // [EN] Expected: Throws BusinessException with CHANGE_REQUEST_ID_REQUIRED error code
        BusinessException exception = assertThrows(BusinessException.class,
                () -> changeRequestService.validateAndPrepareChangeCoordinatorTransition(null, 2L));
        assertThat(exception.getMessage()).isEqualTo(
                ErrorCodeCommon.CHANGE_REQUEST_ID_REQUIRED.getMessage());
    }

    @Test
    void validateAndPrepareChangeCoordinatorTransition_negativeTest_changeRequestNotFound() {
        // [EN] Input: changeRequestId = 1L, nextChangeStatusId = 2L, changeRequestRepository.findById(1L) returns Optional.empty()
        // [EN] Expected: Throws BusinessException with CHANGE_REQUEST_NOT_FOUND error code
        when(changeRequestRepository.findById(1L)).thenReturn(Optional.empty());
        BusinessException exception = assertThrows(BusinessException.class,
                () -> changeRequestService.validateAndPrepareChangeCoordinatorTransition(1L, 2L));
        assertThat(exception.getMessage()).isEqualTo(
                String.format(ErrorCodeCommon.CHANGE_REQUEST_NOT_FOUND.getMessage(), 1L));
        verify(changeRequestRepository).findById(1L);
    }

    @Test
    void validateAndPrepareChangeCoordinatorTransition_negativeTest_changeTemplateIdMissing() {
        // [EN] Input: changeRequestId = 1L, nextChangeStatusId = 2L, changeRequestEntity has null changeTemplateId
        // [EN] Expected: Throws BusinessException with CHANGE_TEMPLATE_ID_MISSING error code
        ChangeRequestEntity changeRequestEntity = new ChangeRequestEntity();
        changeRequestEntity.setId(1L);
        changeRequestEntity.setChangeTemplateId(null);
        when(changeRequestRepository.findById(1L)).thenReturn(Optional.of(changeRequestEntity));
        BusinessException exception = assertThrows(BusinessException.class,
                () -> changeRequestService.validateAndPrepareChangeCoordinatorTransition(1L, 2L));
        assertThat(exception.getMessage()).isEqualTo(
                String.format(ErrorCodeCommon.CHANGE_TEMPLATE_ID_MISSING.getMessage(), null));
        verify(changeRequestRepository).findById(1L);
    }

    @Test
    void validateAndPrepareChangeCoordinatorTransition_negativeTest_changeTemplateNotFound() {
        // [EN] Input: changeRequestId = 1L, nextChangeStatusId = 2L, changeTemplateService.findById(1L) returns null
        // [EN] Expected: Throws BusinessException with CHANGE_TEMPLATE_NOT_FOUND error code
        ChangeRequestEntity changeRequestEntity = new ChangeRequestEntity();
        changeRequestEntity.setId(1L);
        changeRequestEntity.setChangeTemplateId(1L);
        when(changeRequestRepository.findById(1L)).thenReturn(Optional.of(changeRequestEntity));
        when(changeTemplateService.findById(1L)).thenReturn(null);
        BusinessException exception = assertThrows(BusinessException.class,
                () -> changeRequestService.validateAndPrepareChangeCoordinatorTransition(1L, 2L));
        assertThat(exception.getMessage()).isEqualTo(
                String.format(ErrorCodeCommon.CHANGE_TEMPLATE_NOT_FOUND.getMessage(), 1L));
        verify(changeRequestRepository).findById(1L);
        verify(changeTemplateService).findById(1L);
    }

    @Test
    void validateAndPrepareChangeCoordinatorTransition_negativeTest_changeFlowConfigurationError() {
        // [EN] Input: changeRequestId = 1L, nextChangeStatusId = 2L, changeTemplateModel has null changeFlowId
        // [EN] Expected: Throws BusinessException with CHANGE_FLOW_CONFIGURATION_ERROR error code
        ChangeRequestEntity changeRequestEntity = new ChangeRequestEntity();
        changeRequestEntity.setId(1L);
        changeRequestEntity.setChangeTemplateId(1L);
        ChangeTemplateModel changeTemplateModel = new ChangeTemplateModel();
        changeTemplateModel.setId(1L);
        changeTemplateModel.setChangeFlowId(null);
        when(changeRequestRepository.findById(1L)).thenReturn(Optional.of(changeRequestEntity));
        when(changeTemplateService.findById(1L)).thenReturn(changeTemplateModel);
        BusinessException exception = assertThrows(BusinessException.class,
                () -> changeRequestService.validateAndPrepareChangeCoordinatorTransition(1L, 2L));
        assertThat(exception.getMessage()).isEqualTo(
                String.format(ErrorCodeCommon.CHANGE_FLOW_CONFIGURATION_ERROR.getMessage(), null));
        verify(changeRequestRepository).findById(1L);
        verify(changeTemplateService).findById(1L);
    }

    @Test
    void validateAndPrepareChangeCoordinatorTransition_negativeTest_noValidNextStatusesFound() {
        // [EN] Input: changeRequestId = 1L, nextChangeStatusId = 2L, findRemainingStatusesInSameStage returns null
        // [EN] Expected: Throws BusinessException with NO_VALID_NEXT_STATUSES_FOUND error code
        ChangeRequestEntity changeRequestEntity = new ChangeRequestEntity();
        changeRequestEntity.setId(1L);
        changeRequestEntity.setChangeTemplateId(1L);
        changeRequestEntity.setChangeStatusId(1L);
        ChangeTemplateModel changeTemplateModel = new ChangeTemplateModel();
        changeTemplateModel.setId(1L);
        changeTemplateModel.setChangeFlowId(1L);
        when(changeRequestRepository.findById(1L)).thenReturn(Optional.of(changeRequestEntity));
        when(changeTemplateService.findById(1L)).thenReturn(changeTemplateModel);
        when(changeStatusService.findRemainingStatusesInSameStage(1L)).thenReturn(null);
        BusinessException exception = assertThrows(BusinessException.class,
                () -> changeRequestService.validateAndPrepareChangeCoordinatorTransition(1L, 2L));
        assertThat(exception.getMessage()).isEqualTo(
                String.format(ErrorCodeCommon.NO_VALID_NEXT_STATUSES_FOUND.getMessage(), 1L));
        verify(changeRequestRepository).findById(1L);
        verify(changeTemplateService).findById(1L);
        verify(changeStatusService).findRemainingStatusesInSameStage(1L);
    }

    @Test
    void validateAndPrepareChangeCoordinatorTransition_negativeTest_invalidChangeStatus() {
        // [EN] Input: changeRequestId = 1L, nextChangeStatusId = null
        // [EN] Expected: Throws BusinessException with INVALID_CHANGE_STATUS error code
        ChangeRequestEntity changeRequestEntity = new ChangeRequestEntity();
        changeRequestEntity.setId(1L);
        changeRequestEntity.setChangeTemplateId(1L);
        ChangeTemplateModel changeTemplateModel = new ChangeTemplateModel();
        changeTemplateModel.setId(1L);
        changeTemplateModel.setChangeFlowId(1L);
        when(changeRequestRepository.findById(1L)).thenReturn(Optional.of(changeRequestEntity));
        when(changeTemplateService.findById(1L)).thenReturn(changeTemplateModel);
        BusinessException exception = assertThrows(BusinessException.class,
                () -> changeRequestService.validateAndPrepareChangeCoordinatorTransition(1L, null));
        assertThat(exception.getMessage()).isEqualTo(
                ErrorCodeCommon.INVALID_CHANGE_STATUS.getMessage());
    }

    @Test
    void validateAndPrepareChangeCoordinatorTransition_negativeTest_nextStatusNotInStage() {
        // [EN] Input: changeRequestId = 1L, nextChangeStatusId = 2L, remainingStatusesInSameStage does not contain nextChangeStatusId
        // [EN] Expected: Throws BusinessException with NEXT_STATUS_NOT_IN_STAGE error code
        ChangeRequestEntity changeRequestEntity = new ChangeRequestEntity();
        changeRequestEntity.setId(1L);
        changeRequestEntity.setChangeTemplateId(1L);
        changeRequestEntity.setChangeStatusId(1L);
        ChangeTemplateModel changeTemplateModel = new ChangeTemplateModel();
        changeTemplateModel.setId(1L);
        changeTemplateModel.setChangeFlowId(1L);
        List<ChangeStatusModel> remainingStatusesInSameStage = new ArrayList<>();
        ChangeStatusModel otherStatus = new ChangeStatusModel();
        otherStatus.setId(3L);
        remainingStatusesInSameStage.add(otherStatus);
        when(changeRequestRepository.findById(1L)).thenReturn(Optional.of(changeRequestEntity));
        when(changeTemplateService.findById(1L)).thenReturn(changeTemplateModel);
        when(changeStatusService.findRemainingStatusesInSameStage(1L)).thenReturn(
                remainingStatusesInSameStage);
        BusinessException exception = assertThrows(BusinessException.class,
                () -> changeRequestService.validateAndPrepareChangeCoordinatorTransition(1L, 2L));
        assertThat(exception.getMessage()).isEqualTo(
                String.format(ErrorCodeCommon.NEXT_STATUS_NOT_IN_STAGE.getMessage(), 2L, 1L));
        verify(changeRequestRepository).findById(1L);
        verify(changeTemplateService).findById(1L);
        verify(changeStatusService).findRemainingStatusesInSameStage(1L);
    }

    @Test
    void processChangeRequestCoordinatorTransition_positiveTest() {
        // [EN] Input: changeRequestId = 1L, changeStatusId = 2L, valid mocks
        // [EN] Expected: Returns ChangeRequestModel, verifies interactions with mocks
        Long changeRequestId = 1L;
        Long changeStatusId = 2L;
        FlowTransitionDetail flowTransitionDetail = FlowTransitionDetail.builder().changeFlowId(1L)
                .changeRequest(new ChangeRequestEntity()).currentChangeFlowNodeHandleId("handleId")
                .build();
        IndexedChangeFlowDataModel flowData = new IndexedChangeFlowDataModel();
        Map<String, FlowEdgeModel> indexedEdges = new HashMap<>();
        FlowEdgeModel edgeModel = new FlowEdgeModel();
        edgeModel.setChangeFlowId(1L);
        indexedEdges.put("handleId", edgeModel);
        flowData.setIndexedEdges(indexedEdges);
        ChangeRequestModel changeRequestModel = new ChangeRequestModel();
        when(changeRequestService.validateAndPrepareChangeCoordinatorTransition(changeRequestId,
                changeStatusId)).thenReturn(flowTransitionDetail);
        when(flowManagementService.getFlowDataByChangeFlowId(1L)).thenReturn(flowData);
        when(flowManagementService.getOrDefaultEdgeByNodeHandleId(1L, "handleId",
                indexedEdges)).thenReturn(edgeModel);
        doNothing().when(changeRequestService)
                .recursiveProcessChangeRequestTransition(any(ChangeRequestEntity.class),
                        any(FlowEdgeModel.class), any(Map.class));
        when(changeRequestMapper.toDto(any(ChangeRequestEntity.class))).thenReturn(
                changeRequestModel);
        ChangeRequestModel result =
                changeRequestService.processChangeRequestCoordinatorTransition(changeRequestId,
                        changeStatusId);
        assertThat(result).isEqualTo(changeRequestModel);
        verify(changeRequestService).validateAndPrepareChangeCoordinatorTransition(changeRequestId,
                changeStatusId);
        verify(flowManagementService).getFlowDataByChangeFlowId(1L);
        verify(flowManagementService).getOrDefaultEdgeByNodeHandleId(1L, "handleId", indexedEdges);
        verify(changeRequestService).recursiveProcessChangeRequestTransition(
                any(ChangeRequestEntity.class), any(FlowEdgeModel.class), any(Map.class));
        verify(changeRequestMapper).toDto(any(ChangeRequestEntity.class));
    }

    @Test
    void recursiveProcessChangeRequestTransition_positiveTest_endNode() {
        // [EN] Input: changeRequest, edgeModel with targetNode of type END
        // [EN] Expected: Calls handleStopTransitionAndUpdateChange, verifies interactions
        ChangeRequestEntity changeRequest = new ChangeRequestEntity();
        changeRequest.setId(1L);
        FlowEdgeModel edgeModel = new FlowEdgeModel();
        FlowNodeModel targetNode = new FlowNodeModel();
        targetNode.setType(NodeType.END);
        edgeModel.setTargetNode(targetNode);
        Map<String, FlowEdgeModel> indexedEdges = new HashMap<>();
        doNothing().when(changeRequestService)
                .handleStopTransitionAndUpdateChange(anyLong(), any(ChangeRequestEntity.class),
                        any(FlowEdgeModel.class));
        changeRequestService.recursiveProcessChangeRequestTransition(changeRequest, edgeModel,
                indexedEdges);
        verify(changeRequestService).handleStopTransitionAndUpdateChange(1L, changeRequest,
                edgeModel);
    }

    @Test
    void recursiveProcessChangeRequestTransition_positiveTest_changeStageNode() {
        // [EN] Input: changeRequest, edgeModel with targetNode of type CHANGE_STAGE, newStatusId != null
        // [EN] Expected: Calls changeRequestHistoryService.createHistoryRecord and recursiveProcessChangeRequestTransition, verifies interactions
        ChangeRequestEntity changeRequest = new ChangeRequestEntity();
        changeRequest.setId(1L);
        changeRequest.setChangeStatusId(1L);
        changeRequest.setChangeFlowNodeStrId("node1");
        FlowEdgeModel edgeModel = new FlowEdgeModel();
        FlowNodeModel targetNode = new FlowNodeModel();
        targetNode.setType(NodeType.UNKNOWN);
        edgeModel.setTargetNode(targetNode);
        ParsedNodeHandleModel targetHandle = new ParsedNodeHandleModel();
        targetHandle.setChangeStatusId(2L);
        edgeModel.setTargetHandle(targetHandle);
        ParsedNodeHandleModel sourceHandle = new ParsedNodeHandleModel();
        sourceHandle.setCustomAction(ApprovalResultStatus.UNKNOWN);
        edgeModel.setSourceHandle(sourceHandle);
        edgeModel.setTargetNodeId("node2");
        edgeModel.setChangeFlowId(1L);
        Map<String, FlowEdgeModel> indexedEdges = new HashMap<>();
        FlowEdgeModel nextEdgeModel = new FlowEdgeModel();
        indexedEdges.put("2" + FlowConstants.HANDLE_SEPARATOR + FlowConstants.OUTPUT_KEYWORD,
                nextEdgeModel);
        when(flowManagementService.getOrDefaultEdgeByNodeHandleId(1L,
                "2" + FlowConstants.HANDLE_SEPARATOR + FlowConstants.OUTPUT_KEYWORD,
                indexedEdges)).thenReturn(nextEdgeModel);
        doNothing().when(changeRequestHistoryService)
                .createHistoryRecord(any(ChangeRequestHistoryModel.class));
        doNothing().when(changeRequestService)
                .recursiveProcessChangeRequestTransition(any(ChangeRequestEntity.class),
                        any(FlowEdgeModel.class), any(Map.class));
        changeRequestService.recursiveProcessChangeRequestTransition(changeRequest, edgeModel,
                indexedEdges);
        verify(changeRequestHistoryService).createHistoryRecord(
                any(ChangeRequestHistoryModel.class));
        verify(changeRequestService).recursiveProcessChangeRequestTransition(changeRequest,
                nextEdgeModel, indexedEdges);
    }

}
