package com.example.demo.service.impl;

import com.example.demo.entity.entity.ChangeRequestRoleEntity;
import com.example.demo.mapper.ChangeRequestRoleMapper;
import com.example.demo.model.ChangeFlowNodeModel;
import com.example.demo.model.ChangeRequestRoleModel;
import com.example.demo.model.ChangeRequestRoleUserModel;
import com.example.demo.model.ChangeRequestWorkflowModel;
import com.example.demo.repository.ChangeRequestRoleRepository;
import com.example.demo.service.ChangeFlowNodeService;
import com.example.demo.service.ChangeRequestRoleUserService;
import com.example.demo.service.ChangeRequestWorkflowService;
import com.example.demo.service.dto.BusinessException;
import com.example.demo.service.dto.ErrorCodeCommon;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.*;
import java.util.stream.Collectors;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
/**
 * Generated by K-tool
 * Created date: 2025-06-03
 */
class ChangeRequestRoleServiceImplTest {

    @Mock
    private ChangeRequestRoleRepository repository;

    @Mock
    private ChangeRequestRoleUserService changeRequestRoleUserService;

    @Mock
    private ChangeRequestRoleMapper changeRequestRoleMapper;

    @Mock
    private ChangeFlowNodeService changeFlowNodeService;

    @Mock
    private ChangeRequestWorkflowService changeRequestWorkflowService;

    @InjectMocks
    private ChangeRequestRoleServiceImpl changeRequestRoleService;

    @BeforeEach
    void setUp() {
        // Initialize mocks and class under test
    }

    @Test
    void saveList_positiveTest() {
        // [EN] Input: A valid changeRequestId (1L) and a list of ChangeRequestRoleModel with valid data. Mocks are set up to return a saved ChangeRequestRoleEntity.
        // [EN] Expected: The method should save the roles and associated users, and then verify that the necessary methods of the dependencies are called.
        Long changeRequestId = 1L;
        List<ChangeRequestRoleModel> roles = new ArrayList<>();
        ChangeRequestRoleModel role1 = ChangeRequestRoleModel.builder()
                .changeFlowNodeId(10L)
                .changeRequestWorkflowId(20L)
                .cabGroup(1)
                .users(List.of(ChangeRequestRoleUserModel.builder().username("user1").build()))
                .build();
        roles.add(role1);
        ChangeRequestRoleEntity roleEntity = new ChangeRequestRoleEntity();
        roleEntity.setId(1L);

        when(changeRequestRoleMapper.toEntity(any(ChangeRequestRoleModel.class))).thenReturn(roleEntity);
        when(repository.save(any(ChangeRequestRoleEntity.class))).thenReturn(roleEntity);
        doNothing().when(changeRequestRoleUserService).saveAll(anyList());

        changeRequestRoleService.saveList(changeRequestId, roles);

        verify(changeRequestRoleUserService).deleteAllByChangeRequestId(changeRequestId);
        verify(repository).deleteAllByChangeRequestId(changeRequestId);
        verify(repository).save(any(ChangeRequestRoleEntity.class));
        verify(changeRequestRoleUserService).saveAll(anyList());
    }

    @Test
    void saveList_nullChangeRequestIdTest() {
        // [EN] Input: A null changeRequestId.
        // [EN] Expected: A BusinessException with ErrorCodeCommon.ID_NOT_FOUND should be thrown.
        Long changeRequestId = null;
        List<ChangeRequestRoleModel> roles = new ArrayList<>();

        BusinessException exception = assertThrows(BusinessException.class, () -> {
            changeRequestRoleService.saveList(changeRequestId, roles);
        });

        assertThat(exception.getMessage()).isEqualTo(ErrorCodeCommon.ID_NOT_FOUND.getMessage());
    }

    @Test
    void saveList_emptyRolesTest() {
        // [EN] Input: A valid changeRequestId (1L) and an empty list of ChangeRequestRoleModel.
        // [EN] Expected: The method should not save any roles or users, but should still call delete methods.
        Long changeRequestId = 1L;
        List<ChangeRequestRoleModel> roles = new ArrayList<>();

        changeRequestRoleService.saveList(changeRequestId, roles);

        verify(changeRequestRoleUserService).deleteAllByChangeRequestId(changeRequestId);
        verify(repository).deleteAllByChangeRequestId(changeRequestId);
        verify(repository, never()).save(any());
        verify(changeRequestRoleUserService, never()).saveAll(any());
    }

    @Test
    void saveList_nullRolesTest() {
        // [EN] Input: A valid changeRequestId (1L) and a null list of ChangeRequestRoleModel.
        // [EN] Expected: The method should not save any roles or users, but should still call delete methods.
        Long changeRequestId = 1L;
        List<ChangeRequestRoleModel> roles = null;

        changeRequestRoleService.saveList(changeRequestId, roles);

        verify(changeRequestRoleUserService).deleteAllByChangeRequestId(changeRequestId);
        verify(repository).deleteAllByChangeRequestId(changeRequestId);
        verify(repository, never()).save(any());
        verify(changeRequestRoleUserService, never()).saveAll(any());
    }

    @Test
    void findAllByChangeRequestId_positiveTest() {
        // [EN] Input: A valid changeRequestId (1L) for which roles exist. Mocks are set up to return a list of ChangeRequestRoleEntity and ChangeRequestRoleUserModel.
        // [EN] Expected: The method should return a list of ChangeRequestRoleModel with associated users.
        Long changeRequestId = 1L;
        List<ChangeRequestRoleEntity> roles = new ArrayList<>();
        ChangeRequestRoleEntity roleEntity = new ChangeRequestRoleEntity();
        roleEntity.setId(1L);
        roles.add(roleEntity);
        List<ChangeRequestRoleUserModel> users = new ArrayList<>();
        ChangeRequestRoleUserModel userModel = ChangeRequestRoleUserModel.builder().changeRequestRoleId(1L).username("user1").build();
        users.add(userModel);

        when(repository.existsByChangeRequestId(changeRequestId)).thenReturn(true);
        when(repository.findAllByChangeRequestId(changeRequestId)).thenReturn(roles);
        when(changeRequestRoleUserService.findAllByChangeRequestId(changeRequestId)).thenReturn(users);
        when(changeRequestRoleMapper.toDto(any(ChangeRequestRoleEntity.class), anyList())).thenReturn(ChangeRequestRoleModel.builder().id(1L).users(users).build());

        List<ChangeRequestRoleModel> result = changeRequestRoleService.findAllByChangeRequestId(changeRequestId);

        assertThat(result).hasSize(1);
        assertThat(result.get(0).getId()).isEqualTo(1L);
        assertThat(result.get(0).getUsers()).hasSize(1);
        assertThat(result.get(0).getUsers().get(0).getUsername()).isEqualTo("user1");
    }

    @Test
    void findAllByChangeRequestId_nullChangeRequestIdTest() {
        // [EN] Input: A null changeRequestId.
        // [EN] Expected: A BusinessException with ErrorCodeCommon.ID_NOT_FOUND should be thrown.
        Long changeRequestId = null;

        BusinessException exception = assertThrows(BusinessException.class, () -> {
            changeRequestRoleService.findAllByChangeRequestId(changeRequestId);
        });

        assertThat(exception.getMessage()).isEqualTo(ErrorCodeCommon.ID_NOT_FOUND.getMessage());
    }

    @Test
    void findAllByChangeRequestId_changeRequestIdNotFoundTest() {
        // [EN] Input: A valid changeRequestId (1L) for which no roles exist.
        // [EN] Expected: A BusinessException with ErrorCodeCommon.CHANGE_REQUEST_ID_NOT_FOUND should be thrown.
        Long changeRequestId = 1L;

        when(repository.existsByChangeRequestId(changeRequestId)).thenReturn(false);

        BusinessException exception = assertThrows(BusinessException.class, () -> {
            changeRequestRoleService.findAllByChangeRequestId(changeRequestId);
        });

        assertThat(exception.getMessage()).isEqualTo(ErrorCodeCommon.CHANGE_REQUEST_ID_NOT_FOUND.getMessage());
    }

    @Test
    void validateList_positiveTest() {
        // [EN] Input: A valid list of ChangeRequestRoleModel with valid changeFlowNodeId and changeRequestWorkflowId. Mocks are set up to return non-empty maps.
        // [EN] Expected: The method should not throw any exception.
        List<ChangeRequestRoleModel> roles = new ArrayList<>();
        ChangeRequestRoleModel role1 = ChangeRequestRoleModel.builder()
                .changeFlowNodeId(10L)
                .changeRequestWorkflowId(20L)
                .users(Collections.emptyList())
                .build();
        roles.add(role1);

        Map<Long, ChangeFlowNodeModel> changeFlowNodeModelMap = new HashMap<>();
        changeFlowNodeModelMap.put(10L, new ChangeFlowNodeModel());
        Map<Long, ChangeRequestWorkflowModel> changeRequestWorkflowModelMap = new HashMap<>();
        changeRequestWorkflowModelMap.put(20L, new ChangeRequestWorkflowModel());

        when(changeFlowNodeService.findByIdIn(anyList())).thenReturn(changeFlowNodeModelMap);
        when(changeRequestWorkflowService.findByIdIn(anyList())).thenReturn(changeRequestWorkflowModelMap);
        doNothing().when(changeRequestRoleUserService).validateList(anyList());

        changeRequestRoleService.validateList(roles);

        verify(changeFlowNodeService).findByIdIn(anyList());
        verify(changeRequestWorkflowService).findByIdIn(anyList());
        verify(changeRequestRoleUserService).validateList(anyList());
    }

    @Test
    void validateList_nullRolesTest() {
        // [EN] Input: A null list of ChangeRequestRoleModel.
        // [EN] Expected: The method should return without throwing any exception.
        List<ChangeRequestRoleModel> roles = null;

        changeRequestRoleService.validateList(roles);

        verify(changeFlowNodeService, never()).findByIdIn(anyList());
        verify(changeRequestWorkflowService, never()).findByIdIn(anyList());
    }

    @Test
    void validateList_emptyRolesTest() {
        // [EN] Input: An empty list of ChangeRequestRoleModel.
        // [EN] Expected: The method should return without throwing any exception.
        List<ChangeRequestRoleModel> roles = new ArrayList<>();

        changeRequestRoleService.validateList(roles);

        verify(changeFlowNodeService, never()).findByIdIn(anyList());
        verify(changeRequestWorkflowService, never()).findByIdIn(anyList());
    }

    @Test
    void validateList_nullChangeFlowNodeIdTest() {
        // [EN] Input: A list of ChangeRequestRoleModel with a null changeFlowNodeId.
        // [EN] Expected: A BusinessException with ErrorCodeCommon.CHANGE_FLOW_NODE_ID_REQUIRED should be thrown.
        List<ChangeRequestRoleModel> roles = new ArrayList<>();
        ChangeRequestRoleModel role1 = ChangeRequestRoleModel.builder()
                .changeFlowNodeId(null)
                .changeRequestWorkflowId(20L)
                .users(Collections.emptyList())
                .build();
        roles.add(role1);

        BusinessException exception = assertThrows(BusinessException.class, () -> {
            changeRequestRoleService.validateList(roles);
        });

        assertThat(exception.getMessage()).isEqualTo(ErrorCodeCommon.CHANGE_FLOW_NODE_ID_REQUIRED.getMessage());
    }

    @Test
    void validateList_nullChangeRequestWorkflowIdTest() {
        // [EN] Input: A list of ChangeRequestRoleModel with a null changeRequestWorkflowId.
        // [EN] Expected: A BusinessException with ErrorCodeCommon.CHANGE_REQUEST_WORKFLOW_ID_REQUIRED should be thrown.
        List<ChangeRequestRoleModel> roles = new ArrayList<>();
        ChangeRequestRoleModel role1 = ChangeRequestRoleModel.builder()
                .changeFlowNodeId(10L)
                .changeRequestWorkflowId(null)
                .users(Collections.emptyList())
                .build();
        roles.add(role1);

        BusinessException exception = assertThrows(BusinessException.class, () -> {
            changeRequestRoleService.validateList(roles);
        });

        assertThat(exception.getMessage()).isEqualTo(ErrorCodeCommon.CHANGE_REQUEST_WORKFLOW_ID_REQUIRED.getMessage());
    }

    @Test
    void validateList_changeFlowNodeIdNotFoundTest() {
        // [EN] Input: A list of ChangeRequestRoleModel with a changeFlowNodeId that does not exist in the mock map.
        // [EN] Expected: A BusinessException with ErrorCodeCommon.CHANGE_FLOW_NODE_ID_NOT_FOUND should be thrown.
        List<ChangeRequestRoleModel> roles = new ArrayList<>();
        ChangeRequestRoleModel role1 = ChangeRequestRoleModel.builder()
                .changeFlowNodeId(10L)
                .changeRequestWorkflowId(20L)
                .users(Collections.emptyList())
                .build();
        roles.add(role1);

        Map<Long, ChangeFlowNodeModel> changeFlowNodeModelMap = new HashMap<>();
        when(changeFlowNodeService.findByIdIn(anyList())).thenReturn(changeFlowNodeModelMap);
        Map<Long, ChangeRequestWorkflowModel> changeRequestWorkflowModelMap = new HashMap<>();
        changeRequestWorkflowModelMap.put(20L, new ChangeRequestWorkflowModel());
        when(changeRequestWorkflowService.findByIdIn(anyList())).thenReturn(changeRequestWorkflowModelMap);

        BusinessException exception = assertThrows(BusinessException.class, () -> {
            changeRequestRoleService.validateList(roles);
        });

        assertThat(exception.getMessage()).isEqualTo(ErrorCodeCommon.CHANGE_FLOW_NODE_ID_NOT_FOUND.getMessage());
    }

    @Test
    void validateList_changeRequestWorkflowIdNotFoundTest() {
        // [EN] Input: A list of ChangeRequestRoleModel with a changeRequestWorkflowId that does not exist in the mock map.
        // [EN] Expected: A BusinessException with ErrorCodeCommon.CHANGE_REQUEST_WORKFLOW_ID_NOT_FOUND should be thrown.
        List<ChangeRequestRoleModel> roles = new ArrayList<>();
        ChangeRequestRoleModel role1 = ChangeRequestRoleModel.builder()
                .changeFlowNodeId(10L)
                .changeRequestWorkflowId(20L)
                .users(Collections.emptyList())
                .build();
        roles.add(role1);

        Map<Long, ChangeFlowNodeModel> changeFlowNodeModelMap = new HashMap<>();
        changeFlowNodeModelMap.put(10L, new ChangeFlowNodeModel());
        when(changeFlowNodeService.findByIdIn(anyList())).thenReturn(changeFlowNodeModelMap);
        Map<Long, ChangeRequestWorkflowModel> changeRequestWorkflowModelMap = new HashMap<>();
        when(changeRequestWorkflowService.findByIdIn(anyList())).thenReturn(changeRequestWorkflowModelMap);

        BusinessException exception = assertThrows(BusinessException.class, () -> {
            changeRequestRoleService.validateList(roles);
        });

        assertThat(exception.getMessage()).isEqualTo(ErrorCodeCommon.CHANGE_REQUEST_WORKFLOW_ID_NOT_FOUND.getMessage());
    }
}