package com.example.demo.service.impl;

import com.example.demo.entity.entity.ChangeRequestRoleUserEntity;
import com.example.demo.entity.entity.SysUserEntity;
import com.example.demo.mapper.ChangeRequestRoleUserMapper;
import com.example.demo.model.ChangeRequestRoleUserModel;
import com.example.demo.repository.ChangeRequestRoleUserRepository;
import com.example.demo.service.SysUserService;
import com.example.demo.service.dto.BusinessException;
import com.example.demo.service.dto.ErrorCodeCommon;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.dao.DataAccessException;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
/**
 * Generated by K-tool
 * Created date: 2025-06-03
 */ public class ChangeRequestRoleUserServiceImplTest {

    @Mock
    private ChangeRequestRoleUserRepository changeRequestRoleUserRepository;

    @Mock
    private ChangeRequestRoleUserMapper changeRequestRoleUserMapper;

    @Mock
    private SysUserService sysUserService;

    @InjectMocks
    private ChangeRequestRoleUserServiceImpl changeRequestRoleUserServiceImpl;

    private ChangeRequestRoleUserModel changeRequestRoleUserModel;
    private ChangeRequestRoleUserEntity changeRequestRoleUserEntity;

    @BeforeEach
    void setUp() {
        changeRequestRoleUserModel = new ChangeRequestRoleUserModel();
        changeRequestRoleUserModel.setId(1L);
        changeRequestRoleUserModel.setChangeRequestRoleId(10L);
        changeRequestRoleUserModel.setUsername("testUser");

        changeRequestRoleUserEntity = new ChangeRequestRoleUserEntity();
        changeRequestRoleUserEntity.setId(1L);
        changeRequestRoleUserEntity.setChangeRequestRoleId(10L);
        changeRequestRoleUserEntity.setUsername("testUser");
    }

    @Test
    void save_positiveTest() {
        // [EN] Input: A ChangeRequestRoleUserModel object. Mocks are set up to return a ChangeRequestRoleUserEntity when toEntity is called and to return a saved ChangeRequestRoleUserEntity when save is called on the repository. toDto is set up to return the original ChangeRequestRoleUserModel.
        // [EN] Expected: The method should return the same ChangeRequestRoleUserModel that was passed in. The repository's save method and the mapper's toEntity and toDto methods should be called exactly once.
        when(changeRequestRoleUserMapper.toEntity(changeRequestRoleUserModel)).thenReturn(
                changeRequestRoleUserEntity);
        when(changeRequestRoleUserRepository.save(changeRequestRoleUserEntity)).thenReturn(
                changeRequestRoleUserEntity);
        when(changeRequestRoleUserMapper.toDto(changeRequestRoleUserEntity)).thenReturn(
                changeRequestRoleUserModel);

        ChangeRequestRoleUserModel savedModel =
                changeRequestRoleUserServiceImpl.save(changeRequestRoleUserModel);

        assertThat(savedModel).isEqualTo(changeRequestRoleUserModel);
        verify(changeRequestRoleUserMapper, times(1)).toEntity(changeRequestRoleUserModel);
        verify(changeRequestRoleUserRepository, times(1)).save(changeRequestRoleUserEntity);
        verify(changeRequestRoleUserMapper, times(1)).toDto(changeRequestRoleUserEntity);
    }

    @Test
    void save_nullModelTest() {
        // [EN] Input: A null ChangeRequestRoleUserModel object.
        // [EN] Expected: The method should throw a NullPointerException.
        when(changeRequestRoleUserMapper.toEntity(null)).thenThrow(new NullPointerException());

        assertThrows(NullPointerException.class, () -> changeRequestRoleUserServiceImpl.save(null));
        verify(changeRequestRoleUserMapper, times(1)).toEntity(null);
        verify(changeRequestRoleUserRepository, never()).save(any());
        verify(changeRequestRoleUserMapper, never()).toDto(any());
    }

    @Test
    void save_repositoryThrowsExceptionTest() {
        // [EN] Input: A ChangeRequestRoleUserModel object. The repository's save method is set up to throw a DataAccessException.
        // [EN] Expected: The method should throw the same DataAccessException that was thrown by the repository.
        when(changeRequestRoleUserMapper.toEntity(changeRequestRoleUserModel)).thenReturn(
                changeRequestRoleUserEntity);
        when(changeRequestRoleUserRepository.save(changeRequestRoleUserEntity)).thenThrow(
                new DataAccessException("Simulated exception") {
                });

        assertThrows(DataAccessException.class,
                () -> changeRequestRoleUserServiceImpl.save(changeRequestRoleUserModel));
        verify(changeRequestRoleUserMapper, times(1)).toEntity(changeRequestRoleUserModel);
        verify(changeRequestRoleUserRepository, times(1)).save(changeRequestRoleUserEntity);
        verify(changeRequestRoleUserMapper, never()).toDto(any());
    }

    @Test
    void findAllByChangeRequestId_positiveTest() {
        // [EN] Input: A changeRequestId (123L). The repository is set up to return a list of ChangeRequestRoleUserEntity objects. The mapper is set up to return a ChangeRequestRoleUserModel for each entity.
        // [EN] Expected: The method should return a list of ChangeRequestRoleUserModel objects. The repository's findAllByChangeRequestId method and the mapper's toDto method should be called.
        Long changeRequestId = 123L;
        List<ChangeRequestRoleUserEntity> entityList = new ArrayList<>();
        entityList.add(changeRequestRoleUserEntity);
        List<ChangeRequestRoleUserModel> modelList = new ArrayList<>();
        modelList.add(changeRequestRoleUserModel);

        when(changeRequestRoleUserRepository.findAllByChangeRequestId(changeRequestId)).thenReturn(
                entityList);
        when(changeRequestRoleUserMapper.toDto(changeRequestRoleUserEntity)).thenReturn(
                changeRequestRoleUserModel);

        List<ChangeRequestRoleUserModel> result =
                changeRequestRoleUserServiceImpl.findAllByChangeRequestId(changeRequestId);

        assertThat(result).isEqualTo(modelList);
        verify(changeRequestRoleUserRepository, times(1)).findAllByChangeRequestId(changeRequestId);
        verify(changeRequestRoleUserMapper, times(1)).toDto(changeRequestRoleUserEntity);
    }

    @Test
    void findAllByChangeRequestId_noResultsTest() {
        // [EN] Input: A changeRequestId (456L). The repository is set up to return an empty list.
        // [EN] Expected: The method should return an empty list.
        Long changeRequestId = 456L;
        when(changeRequestRoleUserRepository.findAllByChangeRequestId(changeRequestId)).thenReturn(
                Collections.emptyList());

        List<ChangeRequestRoleUserModel> result =
                changeRequestRoleUserServiceImpl.findAllByChangeRequestId(changeRequestId);

        assertThat(result).isEmpty();
        verify(changeRequestRoleUserRepository, times(1)).findAllByChangeRequestId(changeRequestId);
        verify(changeRequestRoleUserMapper, never()).toDto(any());
    }

    @Test
    void saveAll_positiveTest() {
        // [EN] Input: A list of ChangeRequestRoleUserModel objects. The mapper is set up to return a ChangeRequestRoleUserEntity for each model.
        // [EN] Expected: The method should call the repository's saveAll method with the list of entities.
        List<ChangeRequestRoleUserModel> modelList = new ArrayList<>();
        modelList.add(changeRequestRoleUserModel);
        List<ChangeRequestRoleUserEntity> entityList = new ArrayList<>();
        entityList.add(changeRequestRoleUserEntity);

        when(changeRequestRoleUserMapper.toEntity(changeRequestRoleUserModel)).thenReturn(
                changeRequestRoleUserEntity);

        changeRequestRoleUserServiceImpl.saveAll(modelList);

        verify(changeRequestRoleUserMapper, times(1)).toEntity(changeRequestRoleUserModel);
        verify(changeRequestRoleUserRepository, times(1)).saveAll(entityList);
    }

    @Test
    void saveAll_nullListTest() {
        // [EN] Input: A null list of ChangeRequestRoleUserModel objects.
        // [EN] Expected: The method should return without calling any other methods.
        changeRequestRoleUserServiceImpl.saveAll(null);

        verify(changeRequestRoleUserMapper, never()).toEntity(any());
        verify(changeRequestRoleUserRepository, never()).saveAll(any());
    }

    @Test
    void saveAll_emptyListTest() {
        // [EN] Input: An empty list of ChangeRequestRoleUserModel objects.
        // [EN] Expected: The method should return without calling any other methods.
        changeRequestRoleUserServiceImpl.saveAll(Collections.emptyList());

        verify(changeRequestRoleUserMapper, never()).toEntity(any());
        verify(changeRequestRoleUserRepository, never()).saveAll(any());
    }

    @Test
    void deleteAllByChangeRequestId_positiveTest() {
        // [EN] Input: A changeRequestId (789L).
        // [EN] Expected: The method should call the repository's deleteAllByChangeRequestId method with the changeRequestId.
        Long changeRequestId = 789L;

        changeRequestRoleUserServiceImpl.deleteAllByChangeRequestId(changeRequestId);

        verify(changeRequestRoleUserRepository, times(1)).deleteAllByChangeRequestId(
                changeRequestId);
    }

    @Test
    void validateList_positiveTest() {
        // [EN] Input: A list of ChangeRequestRoleUserModel objects with valid usernames. The sysUserService is set up to return an Optional containing a SysUser for each username.
        // [EN] Expected: The method should return without throwing an exception.
        List<ChangeRequestRoleUserModel> modelList = new ArrayList<>();
        changeRequestRoleUserModel.setUsername("user1");
        modelList.add(changeRequestRoleUserModel);

        when(sysUserService.findByUsername("user1")).thenReturn(Optional.of(new SysUserEntity()));

        changeRequestRoleUserServiceImpl.validateList(modelList);

        verify(sysUserService, times(1)).findByUsername("user1");
    }

    @Test
    void validateList_nullListTest() {
        // [EN] Input: A null list of ChangeRequestRoleUserModel objects.
        // [EN] Expected: The method should return without throwing an exception.
        changeRequestRoleUserServiceImpl.validateList(null);

        verify(sysUserService, never()).findByUsername(anyString());
    }

    @Test
    void validateList_emptyListTest() {
        // [EN] Input: An empty list of ChangeRequestRoleUserModel objects.
        // [EN] Expected: The method should return without throwing an exception.
        changeRequestRoleUserServiceImpl.validateList(Collections.emptyList());

        verify(sysUserService, never()).findByUsername(anyString());
    }

    @Test
    void validateList_usernameNotFoundTest() {
        // [EN] Input: A list of ChangeRequestRoleUserModel objects with an invalid username. The sysUserService is set up to return an empty Optional for the username.
        // [EN] Expected: The method should throw a BusinessException with the USERNAME_NOT_FOUND error code.
        List<ChangeRequestRoleUserModel> modelList = new ArrayList<>();
        changeRequestRoleUserModel.setUsername("invalidUser");
        modelList.add(changeRequestRoleUserModel);

        when(sysUserService.findByUsername("invalidUser")).thenReturn(Optional.empty());

        BusinessException exception = assertThrows(BusinessException.class,
                () -> changeRequestRoleUserServiceImpl.validateList(modelList));
        assertThat(exception.getCode().getCode()).isEqualTo(
                ErrorCodeCommon.USERNAME_NOT_FOUND.getCode());
        verify(sysUserService, times(1)).findByUsername("invalidUser");
    }

    @Test
    void validateList_usernameNullOrEmptyTest() {
        // [EN] Input: A list of ChangeRequestRoleUserModel objects with a null or empty username.
        // [EN] Expected: The method should return without calling sysUserService.findByUsername for the null/empty usernames.
        List<ChangeRequestRoleUserModel> modelList = new ArrayList<>();
        ChangeRequestRoleUserModel model1 = new ChangeRequestRoleUserModel();
        model1.setUsername(null);
        modelList.add(model1);
        ChangeRequestRoleUserModel model2 = new ChangeRequestRoleUserModel();
        model2.setUsername("   ");
        modelList.add(model2);

        changeRequestRoleUserServiceImpl.validateList(modelList);

        verify(sysUserService, never()).findByUsername(anyString());
    }

    @Test
    void validateList_multipleInvalidUsernamesTest() {
        // [EN] Input: A list containing multiple invalid usernames.
        // [EN] Expected: A BusinessException with the USERNAME_NOT_FOUND error and a message containing all the invalid usernames separated by commas.
        List<ChangeRequestRoleUserModel> modelList = new ArrayList<>();
        ChangeRequestRoleUserModel model1 = new ChangeRequestRoleUserModel();
        model1.setUsername("invalidUser1");
        modelList.add(model1);
        ChangeRequestRoleUserModel model2 = new ChangeRequestRoleUserModel();
        model2.setUsername("invalidUser2");
        modelList.add(model2);

        when(sysUserService.findByUsername("invalidUser1")).thenReturn(Optional.empty());
        when(sysUserService.findByUsername("invalidUser2")).thenReturn(Optional.empty());

        BusinessException exception = assertThrows(BusinessException.class,
                () -> changeRequestRoleUserServiceImpl.validateList(modelList));
        assertThat(exception.getCode().getCode()).isEqualTo(
                ErrorCodeCommon.USERNAME_NOT_FOUND.getCode());
        verify(sysUserService, times(1)).findByUsername("invalidUser1");
        verify(sysUserService, times(1)).findByUsername("invalidUser2");
    }
}