package com.example.demo.model;

import com.example.demo.enums.ApprovalResultStatus;
import com.example.demo.enums.HandleType;
import com.example.demo.enums.NodeType;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Generated by K-tool
 * Created date: 2025-06-30
 */
class FlowEdgeModelTest {

    private FlowEdgeModel flowEdgeModel;

    @BeforeEach
    void setUp() {
        flowEdgeModel = new FlowEdgeModel();
    }

    @Test
    void parseHandleString_nullHandleStringTest() {
        // [EN] Input: handleString is null.
        // [EN] Expected: Returns a ParsedNodeHandleModel with all fields null except ApprovalResultStatus which is UNKNOWN.
        ParsedNodeHandleModel result = FlowEdgeModel.parseHandleString(null);
        assertNull(result.getRawHandleId());
        assertNull(result.getType());
        assertNull(result.getChangeStatusId());
        assertNull(result.getNodeId());
        assertEquals(result.getCustomAction(), ApprovalResultStatus.UNKNOWN);

        assertEquals(ApprovalResultStatus.UNKNOWN, result.getCustomAction());
    }

    @Test
    void parseHandleString_emptyHandleStringTest() {
        // [EN] Input: handleString is empty.
        // [EN] Expected: Returns a ParsedNodeHandleModel with all fields null except ApprovalResultStatus which is UNKNOWN.
        ParsedNodeHandleModel result = FlowEdgeModel.parseHandleString("");
        assertNull(result.getRawHandleId());
        assertNull(result.getType());
        assertNull(result.getChangeStatusId());
        assertNull(result.getNodeId());
        assertEquals(result.getCustomAction(), ApprovalResultStatus.UNKNOWN);

        assertEquals(ApprovalResultStatus.UNKNOWN, result.getCustomAction());
    }

    @Test
    void parseHandleString_numericHandleStringTest() {
        // [EN] Input: handleString is a numeric handle string "123-input".
        // [EN] Expected: Returns a ParsedNodeHandleModel with changeStatusId set to 123 and type set to INPUT.
        String handleString = "123-input";
        ParsedNodeHandleModel result = FlowEdgeModel.parseHandleString(handleString);
        assertEquals(123L, result.getChangeStatusId());
        assertEquals(HandleType.INPUT, result.getType());
        assertNull(result.getNodeId());
        assertEquals(result.getCustomAction(), ApprovalResultStatus.UNKNOWN);

        assertEquals(handleString, result.getRawHandleId());
    }

    @Test
    void parseHandleString_numericHandleStringOutputTest() {
        // [EN] Input: handleString is a numeric handle string "123-output".
        // [EN] Expected: Returns a ParsedNodeHandleModel with changeStatusId set to 123 and type set to OUTPUT.
        String handleString = "123-output";
        ParsedNodeHandleModel result = FlowEdgeModel.parseHandleString(handleString);
        assertEquals(123L, result.getChangeStatusId());
        assertEquals(HandleType.OUTPUT, result.getType());
        assertNull(result.getNodeId());
        assertEquals(result.getCustomAction(), ApprovalResultStatus.UNKNOWN);
        assertEquals(handleString, result.getRawHandleId());
    }

    @Test
    void parseHandleString_customApprovalHandleStringTest() {
        // [EN] Input: handleString is a custom approval handle string "task-123-Accept-output".
        // [EN] Expected: Returns a ParsedNodeHandleModel with nodeId set to "task", customAction set to ACCEPT.
        String handleString = "task-123-Accept-output";
        ParsedNodeHandleModel result = FlowEdgeModel.parseHandleString(handleString);
        assertEquals("task", result.getNodeId());
        assertEquals(ApprovalResultStatus.ACCEPT, result.getCustomAction());
        assertNull(result.getChangeStatusId());
        assertEquals(handleString, result.getRawHandleId());
    }

    @Test
    void parseHandleString_customApprovalHandleStringRejectTest() {
        // [EN] Input: handleString is a custom approval handle string "task-123-Reject-output".
        // [EN] Expected: Returns a ParsedNodeHandleModel with nodeId set to "task", customAction set to REJECT.
        String handleString = "task-123-Reject-output";
        ParsedNodeHandleModel result = FlowEdgeModel.parseHandleString(handleString);
        assertEquals("task", result.getNodeId());
        assertEquals(ApprovalResultStatus.REJECT, result.getCustomAction());
        assertNull(result.getChangeStatusId());
        assertEquals(handleString, result.getRawHandleId());
    }

    @Test
    void parseHandleString_nodeIdHandleStringInputTest() {
        // [EN] Input: handleString is a node ID handle string "node1-input".
        // [EN] Expected: Returns a ParsedNodeHandleModel with nodeId set to "node1" and type set to INPUT.
        String handleString = "node1-input";
        ParsedNodeHandleModel result = FlowEdgeModel.parseHandleString(handleString);
        assertEquals("node1", result.getNodeId());
        assertEquals(HandleType.INPUT, result.getType());
        assertNull(result.getChangeStatusId());
        assertEquals(result.getCustomAction(), ApprovalResultStatus.UNKNOWN);

        assertEquals(handleString, result.getRawHandleId());
    }

    @Test
    void parseHandleString_nodeIdHandleStringOutputTest() {
        // [EN] Input: handleString is a node ID handle string "node1-output".
        // [EN] Expected: Returns a ParsedNodeHandleModel with nodeId set to "node1" and type set to OUTPUT.
        String handleString = "node1-output";
        ParsedNodeHandleModel result = FlowEdgeModel.parseHandleString(handleString);
        assertEquals("node1", result.getNodeId());
        assertEquals(HandleType.OUTPUT, result.getType());
        assertNull(result.getChangeStatusId());
        assertEquals(result.getCustomAction(), ApprovalResultStatus.UNKNOWN);

        assertEquals(handleString, result.getRawHandleId());
    }

    @Test
    void parseHandleString_invalidHandleFormatTest() {
        // [EN] Input: handleString is an invalid handle string "invalid".
        // [EN] Expected: Throws BusinessException with ErrorCodeCommon.INVALID_HANDLE_FORMAT.
        String handleString = "invalid";
        BusinessException thrown = assertThrows(BusinessException.class,
                () -> FlowEdgeModel.parseHandleString(handleString));
        assertEquals(ErrorCodeCommon.INVALID_HANDLE_FORMAT.getCode(),
                thrown.getErrorCode().getCode());
    }

    @Test
    void fromSimpleFlowEdge_validSimpleEdgeTest() {
        // [EN] Input: simpleEdge is a valid FlowEdgeRawModel with source "node1", target "node2", sourceHandle "123-input", and targetHandle "node3-output".
        // [EN] Expected: Returns a FlowEdgeModel with corresponding fields set, sourceNode and targetNode with correct ids and types.
        FlowEdgeRawModel simpleEdge = new FlowEdgeRawModel();
        simpleEdge.setId("edge1");
        simpleEdge.setSource("node1");
        simpleEdge.setTarget("node2");
        simpleEdge.setSourceHandle("123-input");
        simpleEdge.setTargetHandle("node3-output");

        FlowEdgeModel result = FlowEdgeModel.fromSimpleFlowEdge(simpleEdge);

        assertEquals("edge1", result.getId());
        assertEquals("node1", result.getSourceNodeId());
        assertEquals("node2", result.getTargetNodeId());
        assertEquals(123L, result.getSourceHandle().getChangeStatusId());
        assertEquals("node3", result.getTargetHandle().getNodeId());
        assertEquals(NodeType.UNKNOWN, result.getSourceNode().getType());
        assertEquals(NodeType.UNKNOWN, result.getTargetNode().getType());
    }

    @Test
    void fromSimpleFlowEdge_nullHandlesTest() {
        // [EN] Input: simpleEdge is a FlowEdgeRawModel with null sourceHandle and targetHandle.
        // [EN] Expected: Returns a FlowEdgeModel with sourceHandle and targetHandle having default values (null fields, UNKNOWN ApprovalResultStatus).
        FlowEdgeRawModel simpleEdge = new FlowEdgeRawModel();
        simpleEdge.setId("edge1");
        simpleEdge.setSource("node1");
        simpleEdge.setTarget("node2");
        simpleEdge.setSourceHandle(null);
        simpleEdge.setTargetHandle(null);

        FlowEdgeModel result = FlowEdgeModel.fromSimpleFlowEdge(simpleEdge);

        assertNull(result.getSourceHandle().getRawHandleId());
        assertNull(result.getTargetHandle().getRawHandleId());
        assertEquals(ApprovalResultStatus.UNKNOWN, result.getSourceHandle().getCustomAction());
        assertEquals(ApprovalResultStatus.UNKNOWN, result.getTargetHandle().getCustomAction());
    }

    @Test
    void fromSimpleFlowEdge_emptyHandlesTest() {
        // [EN] Input: simpleEdge is a FlowEdgeRawModel with empty sourceHandle and targetHandle.
        // [EN] Expected: Returns a FlowEdgeModel with sourceHandle and targetHandle having default values (null fields, UNKNOWN ApprovalResultStatus).
        FlowEdgeRawModel simpleEdge = new FlowEdgeRawModel();
        simpleEdge.setId("edge1");
        simpleEdge.setSource("node1");
        simpleEdge.setTarget("node2");
        simpleEdge.setSourceHandle("");
        simpleEdge.setTargetHandle("");

        FlowEdgeModel result = FlowEdgeModel.fromSimpleFlowEdge(simpleEdge);

        assertNull(result.getSourceHandle().getRawHandleId());
        assertNull(result.getTargetHandle().getRawHandleId());
        assertEquals(ApprovalResultStatus.UNKNOWN, result.getSourceHandle().getCustomAction());
        assertEquals(ApprovalResultStatus.UNKNOWN, result.getTargetHandle().getCustomAction());
    }
}