-- Sequence for GROUP
CREATE SEQUENCE GROUP_SEQ START WITH 1 INCREMENT BY 1;

-- Table: GROUP
CREATE TABLE "GROUP" (
    "ID" NUMBER PRIMARY KEY,
    "NAME" VARCHAR2(255),
    "DESCRIPTION" VARCHAR2(255),
    "CREATED_DATE" TIMESTAMP(6),
    "CREATED_BY" VARCHAR2(255),
    "MODIFIED_DATE" TIMESTAMP(6),
    "MODIFIED_BY" VARCHAR2(255),
    "DELETED" NUMBER
);

-- Sequence for CHANGE_TEMPLATE
CREATE SEQUENCE CHANGE_TEMPLATE_SEQ START WITH 1 INCREMENT BY 1;

-- Table: CHANGE_TEMPLATE
CREATE TABLE CHANGE_TEMPLATE (
    "ID" NUMBER PRIMARY KEY,
    "NAME" VARCHAR2(255),
    "DESCRIPTION" VARCHAR2(255),
    "NOTICE" VARCHAR2(255),
    "ISACTIVE" NUMBER,
    "CREATED_DATE" TIMESTAMP(6),
    "CREATED_BY" VARCHAR2(255),
    "MODIFIED_DATE" TIMESTAMP(6),
    "MODIFIED_BY" VARCHAR2(255),
    "DELETED" NUMBER
);

-- Sequence for CHANGE_TEMPLATE_ROLE
CREATE SEQUENCE CHANGE_TEMPLATE_ROLE_SEQ START WITH 1 INCREMENT BY 1;

-- Table: CHANGE_TEMPLATE_ROLE
CREATE TABLE CHANGE_TEMPLATE_ROLE (
    "ID" NUMBER PRIMARY KEY,
    "CHANGE_TEMPLATE_ID" NUMBER,
    "GROUP_ID" NUMBER,
    "LEVEL" NUMBER, -- 'LEVEL' is a reserved keyword, enclosed in quotes
    "ORDER" NUMBER, -- 'ORDER' is a reserved keyword, enclosed in quotes
    "CREATED_DATE" TIMESTAMP(6),
    "CREATED_BY" VARCHAR2(255),
    "MODIFIED_DATE" TIMESTAMP(6),
    "MODIFIED_BY" VARCHAR2(255)
);

-- Sequence for CHANGE_TEMPLATE_ROLE_USER
CREATE SEQUENCE CHANGE_TEMPLATE_ROLE_USER_SEQ START WITH 1 INCREMENT BY 1;

-- Table: CHANGE_TEMPLATE_ROLE_USER
CREATE TABLE CHANGE_TEMPLATE_ROLE_USER (
    "ID" NUMBER PRIMARY KEY,
    "CHANGE_TEMPLATE_ROLE_ID" NUMBER,
    "USERNAME" VARCHAR2(255),
    "CREATED_DATE" TIMESTAMP(6),
    "CREATED_BY" VARCHAR2(255),
    "MODIFIED_DATE" TIMESTAMP(6),
    "MODIFIED_BY" VARCHAR2(255)
);

-- Sequence for CHANGE_REQUEST
CREATE SEQUENCE CHANGE_REQUEST_SEQ START WITH 1 INCREMENT BY 1;

-- Table: CHANGE_REQUEST
CREATE TABLE CHANGE_REQUEST (
    "ID" NUMBER PRIMARY KEY,
    "CHANGE_TEMPLATE_ID" NUMBER,
    "CREATED_DATE" TIMESTAMP(6),
    "CREATED_BY" VARCHAR2(255),
    "MODIFIED_DATE" TIMESTAMP(6),
    "MODIFIED_BY" VARCHAR2(255),
    "DELETED" NUMBER,
    "STATUS" VARCHAR2(255),
    "TITLE" VARCHAR2(255),
    "DESCRIPTION" VARCHAR2(1000),
    "DUE_DATE" DATE
);

-- Sequence for CHANGE_REQUEST_ROLE
CREATE SEQUENCE CHANGE_REQUEST_ROLE_SEQ START WITH 1 INCREMENT BY 1;

-- Table: CHANGE_REQUEST_ROLE
CREATE TABLE CHANGE_REQUEST_ROLE (
    "ID" NUMBER PRIMARY KEY,
    "CHANGE_REQUEST_ID" NUMBER,
    "GROUP_ID" NUMBER,
    "CREATED_DATE" TIMESTAMP(6),
    "CREATED_BY" VARCHAR2(255),
    "MODIFIED_DATE" TIMESTAMP(6),
    "MODIFIED_BY" VARCHAR2(255)
);

-- Sequence for CHANGE_REQUEST_ROLE_USER
CREATE SEQUENCE CHANGE_REQUEST_ROLE_USER_SEQ START WITH 1 INCREMENT BY 1;

-- Table: CHANGE_REQUEST_ROLE_USER
CREATE TABLE CHANGE_REQUEST_ROLE_USER (
    "ID" NUMBER PRIMARY KEY,
    "CHANGE_REQUEST_ROLE_ID" NUMBER,
    "USERNAME" VARCHAR2(255),
    "CREATED_DATE" TIMESTAMP(6),
    "CREATED_BY" VARCHAR2(255),
    "MODIFIED_DATE" TIMESTAMP(6),
    "MODIFIED_BY" VARCHAR2(255)
);

-- Sequence for SYS_PERMISSION_ROLE
CREATE SEQUENCE SYS_PERMISSION_ROLE_SEQ START WITH 1 INCREMENT BY 1;

-- Table: SYS_PERMISSION_ROLE
CREATE TABLE SYS_PERMISSION_ROLE (
 
    -- Please add the actual column definitions here as they were not provided in the original request.
    -- Example: "ID" NUMBER PRIMARY KEY,
    -- "ROLE_ID" NUMBER,
    -- "PERMISSION_ID" NUMBER
);

-- Sequence for SYS_USER
CREATE SEQUENCE SYS_USER_SEQ START WITH 1 INCREMENT BY 1;

-- Table: SYS_USER
CREATE TABLE SYS_USER (
 
    -- Please add the actual column definitions here as they were not provided in the original request.
    -- Example: "ID" NUMBER PRIMARY KEY,
    -- "USERNAME" VARCHAR2(255),
    -- "EMAIL" VARCHAR2(255)
);