package com.example.demo.controller;

import com.example.demo.model.ChangeTemplateFieldItemDto;
import com.example.demo.model.ChangeTemplateModel;
import com.example.demo.model.PagingRequestModel;
import com.example.demo.service.ChangeTemplateService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
/**
 * Generated by K-tool
 * Created date: 2025-05-22
 */ public class ChangeTemplateControllerTest extends PermissionBaseControllerTest {

    @Mock
    private ChangeTemplateService changeTemplateService;

    @InjectMocks
    private ChangeTemplateController changeTemplateController;

    private ChangeTemplateModel changeTemplateModel;
    private PagingRequestModel pagingRequestModel;
    private ChangeTemplateFieldItemDto changeTemplateFieldItemDto;

    @BeforeEach
    void setUp() {
        changeTemplateModel =
                ChangeTemplateModel.builder().id(1L).name("Template 1").description("Description 1")
                        .build();
        pagingRequestModel = PagingRequestModel.builder().page(0).size(10).build();
        changeTemplateFieldItemDto =
                ChangeTemplateFieldItemDto.builder().id(1L).changeTemplateId(1L).customFieldId(1L)
                        .fieldValue("Value").build();
    }

    /**
     * [EN] Input: Valid PagingRequestModel.
     * [EN] Expected: ResponseEntity with a Page of ChangeTemplateModel and HTTP status 200 OK.
     */
    @Test
    void findPagings_positiveTest() {
        // Arrange
        List<ChangeTemplateModel> changeTemplateList =
                Collections.singletonList(changeTemplateModel);
        Page<ChangeTemplateModel> page = new PageImpl<>(changeTemplateList);
        when(changeTemplateService.findPagings(any(PagingRequestModel.class))).thenReturn(page);

        // Act
        ResponseEntity<Page<ChangeTemplateModel>> response =
                changeTemplateController.findPagings(pagingRequestModel);

        // Assert
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).isEqualTo(page);
        verify(changeTemplateService).findPagings(pagingRequestModel);
    }

    /**
     * [EN] Input: PagingRequestModel with null values. Service returns an empty page.
     * [EN] Expected: ResponseEntity with an empty Page of ChangeTemplateModel and HTTP status 200 OK.
     */
    @Test
    void findPagings_emptyPageTest() {
        // Arrange
        PagingRequestModel pagingRequest = PagingRequestModel.builder().build();
        Page<ChangeTemplateModel> page = new PageImpl<>(new ArrayList<>());
        when(changeTemplateService.findPagings(any(PagingRequestModel.class))).thenReturn(page);

        // Act
        ResponseEntity<Page<ChangeTemplateModel>> response =
                changeTemplateController.findPagings(pagingRequest);

        // Assert
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).isEqualTo(page);
        verify(changeTemplateService).findPagings(pagingRequest);
    }

    /**
     * [EN] Input: List of valid IDs (1L, 2L).
     * [EN] Expected: ResponseEntity with HTTP status 200 OK and no body. Service method deleteByIds is called.
     */
    @Test
    void deleteByIds_positiveTest() {
        // Arrange
        List<Long> ids = List.of(1L, 2L);
        doNothing().when(changeTemplateService).deleteByIds(ids);

        // Act
        ResponseEntity<Void> response = changeTemplateController.deleteByIds(ids);

        // Assert
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        verify(changeTemplateService).deleteByIds(ids);
    }

    /**
     * [EN] Input: Empty list of IDs.
     * [EN] Expected: ResponseEntity with HTTP status 200 OK and no body. Service method deleteByIds is called.
     */
    @Test
    void deleteByIds_emptyListTest() {
        // Arrange
        List<Long> ids = new ArrayList<>();
        doNothing().when(changeTemplateService).deleteByIds(ids);

        // Act
        ResponseEntity<Void> response = changeTemplateController.deleteByIds(ids);

        // Assert
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        verify(changeTemplateService).deleteByIds(ids);
    }

    /**
     * [EN] Input: Valid ID (1L).
     * [EN] Expected: ResponseEntity with ChangeTemplateModel and HTTP status 200 OK.
     */
    @Test
    void findById_positiveTest() {
        // Arrange
        when(changeTemplateService.findById(1L)).thenReturn(changeTemplateModel);

        // Act
        ResponseEntity<ChangeTemplateModel> response = changeTemplateController.findById(1L);

        // Assert
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).isEqualTo(changeTemplateModel);
        verify(changeTemplateService).findById(1L);
    }

    /**
     * [EN] Input: Non-existent ID (999L). Service returns null.
     * [EN] Expected: ResponseEntity with null body, but HTTP status 200 OK (service should throw exception, not return null).
     */
    @Test
    void findById_notFoundTest() {
        // Arrange
        when(changeTemplateService.findById(999L)).thenReturn(null);

        // Act
        ResponseEntity<ChangeTemplateModel> response = changeTemplateController.findById(999L);

        // Assert
        assertThat(response.getStatusCode()).isEqualTo(
                HttpStatus.OK); // Should be 404 Not Found, but service returns null
        assertThat(response.getBody()).isNull();
        verify(changeTemplateService).findById(999L);
    }

    /**
     * [EN] Input: Valid ChangeTemplateModel.
     * [EN] Expected: ResponseEntity with saved ChangeTemplateModel and HTTP status 200 OK.
     */
    @Test
    void save_positiveTest() {
        // Arrange
        when(changeTemplateService.save(any(ChangeTemplateModel.class))).thenReturn(
                changeTemplateModel);

        // Act
        ResponseEntity<ChangeTemplateModel> response =
                changeTemplateController.save(changeTemplateModel);

        // Assert
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).isEqualTo(changeTemplateModel);
        verify(changeTemplateService).save(changeTemplateModel);
    }

    /**
     * [EN] Input: ChangeTemplateModel with null values.
     * [EN] Expected: ResponseEntity with saved ChangeTemplateModel and HTTP status 200 OK.
     */
    @Test
    void save_nullValuesTest() {
        // Arrange
        ChangeTemplateModel templateWithNulls = ChangeTemplateModel.builder().build();
        when(changeTemplateService.save(any(ChangeTemplateModel.class))).thenReturn(
                templateWithNulls);

        // Act
        ResponseEntity<ChangeTemplateModel> response =
                changeTemplateController.save(templateWithNulls);

        // Assert
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).isEqualTo(templateWithNulls);
        verify(changeTemplateService).save(templateWithNulls);
    }

    /**
     * [EN] Input: Valid ID (1L) and ChangeTemplateModel.
     * [EN] Expected: ResponseEntity with saved ChangeTemplateModel and HTTP status 200 OK.
     */
    @Test
    void saveWithId_positiveTest() {
        // Arrange
        when(changeTemplateService.save(anyLong(), any(ChangeTemplateModel.class))).thenReturn(
                changeTemplateModel);

        // Act
        ResponseEntity<ChangeTemplateModel> response =
                changeTemplateController.save(1L, changeTemplateModel);

        // Assert
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).isEqualTo(changeTemplateModel);
        verify(changeTemplateService).save(1L, changeTemplateModel);
    }

    /**
     * [EN] Input: Valid ID (1L) and ChangeTemplateModel with null values.
     * [EN] Expected: ResponseEntity with saved ChangeTemplateModel and HTTP status 200 OK.
     */
    @Test
    void saveWithId_nullValuesTest() {
        // Arrange
        ChangeTemplateModel templateWithNulls = ChangeTemplateModel.builder().build();
        when(changeTemplateService.save(anyLong(), any(ChangeTemplateModel.class))).thenReturn(
                templateWithNulls);

        // Act
        ResponseEntity<ChangeTemplateModel> response =
                changeTemplateController.save(1L, templateWithNulls);

        // Assert
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).isEqualTo(templateWithNulls);
        verify(changeTemplateService).save(1L, templateWithNulls);
    }

    /**
     * [EN] Input: Valid changeTemplateId (1L) and PagingRequestModel.
     * [EN] Expected: ResponseEntity with Page of ChangeTemplateFieldItemDto and HTTP status 200 OK.
     */
    @Test
    void getPaginatedFieldItems_positiveTest() {
        // Arrange
        List<ChangeTemplateFieldItemDto> fieldItemsList =
                Collections.singletonList(changeTemplateFieldItemDto);
        Page<ChangeTemplateFieldItemDto> page = new PageImpl<>(fieldItemsList);
        when(changeTemplateService.getPaginatedFieldItems(anyLong(), anyInt(),
                anyInt())).thenReturn(page);

        // Act
        ResponseEntity<Page<ChangeTemplateFieldItemDto>> response =
                changeTemplateController.getPaginatedFieldItems(1L, pagingRequestModel);

        // Assert
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).isEqualTo(page);
        verify(changeTemplateService).getPaginatedFieldItems(1L, 0, 10);
    }

    /**
     * [EN] Input: Valid changeTemplateId (1L) and null PagingRequestModel.
     * [EN] Expected: ResponseEntity with Page of ChangeTemplateFieldItemDto and HTTP status 200 OK.  Default paging values are used.
     */
    @Test
    void getPaginatedFieldItems_nullPagingTest() {
        // Arrange
        List<ChangeTemplateFieldItemDto> fieldItemsList =
                Collections.singletonList(changeTemplateFieldItemDto);
        Page<ChangeTemplateFieldItemDto> page = new PageImpl<>(fieldItemsList);
        when(changeTemplateService.getPaginatedFieldItems(anyLong(), anyInt(),
                anyInt())).thenReturn(page);

        // Act
        ResponseEntity<Page<ChangeTemplateFieldItemDto>> response =
                changeTemplateController.getPaginatedFieldItems(1L, null);

        // Assert
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).isEqualTo(page);
        verify(changeTemplateService).getPaginatedFieldItems(1L, 0, 10);
    }

    /**
     * [EN] Input: Valid id (1L) and PagingRequestModel.
     * [EN] Expected: ResponseEntity with ChangeTemplateModel and HTTP status 200 OK.
     */
    @Test
    void getDetailWithRoles_positiveTest() {
        // Arrange
        when(changeTemplateService.getDetailWithRoles(anyLong(), anyInt(), anyInt())).thenReturn(
                changeTemplateModel);

        // Act
        ResponseEntity<ChangeTemplateModel> response =
                changeTemplateController.getDetailWithRoles(1L, pagingRequestModel);

        // Assert
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).isEqualTo(changeTemplateModel);
        verify(changeTemplateService).getDetailWithRoles(1L, 0, 10);
    }

    /**
     * [EN] Input: Valid id (1L) and null PagingRequestModel.
     * [EN] Expected: ResponseEntity with ChangeTemplateModel and HTTP status 200 OK. Default paging values are used.
     */
    @Test
    void getDetailWithRoles_nullPagingTest() {
        // Arrange
        when(changeTemplateService.getDetailWithRoles(anyLong(), anyInt(), anyInt())).thenReturn(
                changeTemplateModel);

        // Act
        ResponseEntity<ChangeTemplateModel> response =
                changeTemplateController.getDetailWithRoles(1L, null);

        // Assert
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).isEqualTo(changeTemplateModel);
        verify(changeTemplateService).getDetailWithRoles(1L, 0, 10);
    }

    /**
     * [EN] Input: Non-existent ID (999L) and PagingRequestModel. Service returns null.
     * [EN] Expected: ResponseEntity with HTTP status 404 Not Found.
     */
    @Test
    void getDetailWithRoles_notFoundTest() {
        // Arrange
        when(changeTemplateService.getDetailWithRoles(anyLong(), anyInt(), anyInt())).thenReturn(
                null);

        // Act
        ResponseEntity<ChangeTemplateModel> response =
                changeTemplateController.getDetailWithRoles(999L, pagingRequestModel);

        // Assert
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
        assertThat(response.getBody()).isNull();
        verify(changeTemplateService).getDetailWithRoles(999L, 0, 10);
    }
}