package com.example.demo.controller;

import com.example.demo.constants.ServerUrl;
import com.example.demo.model.ChangeRequestRoleModel;
import com.example.demo.service.ChangeRequestRoleService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import java.util.ArrayList;
import java.util.List;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
/**
 * Generated by K-tool
 * Created date: 2025-06-03
 */
class ChangeRequestControllerTest {

    @Mock
    private ChangeRequestRoleService changeRequestRoleService;

    @InjectMocks
    private ChangeRequestController changeRequestController;

    @BeforeEach
    void setUp() {
        // Initialize mocks and the class under test
    }

    /**
     * [EN] Input: A valid changeRequestId (Long) for which roles exist.
     * [EN] Expected: A ResponseEntity with HttpStatus.OK and a list of ChangeRequestRoleModel objects.
     */
    @Test
    void getAllRolesByChangeRequestId_positiveTest() {
        // Arrange
        Long changeRequestId = 1L;
        List<ChangeRequestRoleModel> expectedRoles = new ArrayList<>();
        ChangeRequestRoleModel role1 = new ChangeRequestRoleModel();
        role1.setId(1L);
        expectedRoles.add(role1);

        when(changeRequestRoleService.findAllByChangeRequestId(changeRequestId)).thenReturn(expectedRoles);

        // Act
        ResponseEntity<List<ChangeRequestRoleModel>> responseEntity =
                changeRequestController.getAllRolesByChangeRequestId(changeRequestId);

        // Assert
        assertEquals(HttpStatus.OK, responseEntity.getStatusCode());
        assertEquals(expectedRoles, responseEntity.getBody());
        verify(changeRequestRoleService, times(1)).findAllByChangeRequestId(changeRequestId);
    }

    /**
     * [EN] Input: A changeRequestId (Long) for which no roles exist.
     * [EN] Expected: A ResponseEntity with HttpStatus.OK and an empty list.
     */
    @Test
    void getAllRolesByChangeRequestId_noRolesTest() {
        // Arrange
        Long changeRequestId = 2L;
        List<ChangeRequestRoleModel> expectedRoles = new ArrayList<>(); // Empty list

        when(changeRequestRoleService.findAllByChangeRequestId(changeRequestId)).thenReturn(expectedRoles);

        // Act
        ResponseEntity<List<ChangeRequestRoleModel>> responseEntity =
                changeRequestController.getAllRolesByChangeRequestId(changeRequestId);

        // Assert
        assertEquals(HttpStatus.OK, responseEntity.getStatusCode());
        assertEquals(expectedRoles, responseEntity.getBody());
        verify(changeRequestRoleService, times(1)).findAllByChangeRequestId(changeRequestId);
    }

    /**
     * [EN] Input: A negative changeRequestId (Long).
     * [EN] Expected: A ResponseEntity with HttpStatus.OK and an empty list (assuming the service handles negative IDs gracefully).
     */
    @Test
    void getAllRolesByChangeRequestId_negativeIdTest() {
        // Arrange
        Long changeRequestId = -1L;
        List<ChangeRequestRoleModel> expectedRoles = new ArrayList<>();

        when(changeRequestRoleService.findAllByChangeRequestId(changeRequestId)).thenReturn(expectedRoles);

        // Act
        ResponseEntity<List<ChangeRequestRoleModel>> responseEntity =
                changeRequestController.getAllRolesByChangeRequestId(changeRequestId);

        // Assert
        assertEquals(HttpStatus.OK, responseEntity.getStatusCode());
        assertEquals(expectedRoles, responseEntity.getBody());
        verify(changeRequestRoleService, times(1)).findAllByChangeRequestId(changeRequestId);
    }

    /**
     * [EN] Input: A changeRequestId (Long) where the service throws an exception.
     * [EN] Expected: The exception is caught and re-thrown, or a default empty list is returned with HTTP 200.  This test case assumes the controller does NOT handle exceptions and allows them to propagate.
     */
    @Test
    void getAllRolesByChangeRequestId_serviceThrowsExceptionTest() {
        // Arrange
        Long changeRequestId = 3L;
        when(changeRequestRoleService.findAllByChangeRequestId(changeRequestId))
                .thenThrow(new RuntimeException("Simulated service exception"));

        // Act & Assert
        try {
            changeRequestController.getAllRolesByChangeRequestId(changeRequestId);
        } catch (RuntimeException e) {
            assertEquals("Simulated service exception", e.getMessage());
            verify(changeRequestRoleService, times(1)).findAllByChangeRequestId(changeRequestId);
            return;
        }
        //If no exception is thrown, the test fails.
        throw new AssertionError("Expected RuntimeException was not thrown.");
    }
}