//package com.example.utils;
//
//import com.example.demo.model.ChangeRequestRoleModel;
//import com.example.demo.model.ChangeRequestRoleUserModel;
//import org.junit.jupiter.api.BeforeEach;
//import org.junit.jupiter.api.Test;
//import org.mockito.MockitoAnnotations;
//
//import java.util.ArrayList;
//import java.util.List;
//
//import static org.junit.jupiter.api.Assertions.assertEquals;
//import static org.junit.jupiter.api.Assertions.assertNull;
//
/// **
// * Generated by K-tool
// * Created date: 2025-06-24
// */
//class UtilsTest {
//
//    private ChangeRequestRoleUtils utils;
//
//    @BeforeEach
//    void setUp() {
//        MockitoAnnotations.openMocks(this);
//        utils = new ChangeRequestRoleUtils();
//    }
//
//
//    /**
//     * [EN] Input: Null list of ChangeRequestRoleModel.
//     * [EN] Expected: Method should return without any exception and no modification to the null list.
//     */
//    @Test
//    void groupAndSortCabUserGroups2_nullListTest() {
//        // Arrange
//        List<ChangeRequestRoleModel> items = null;
//
//        // Act
//        utils.groupAndSortCabUserGroups2(items);
//
//        // Assert
//        assertNull(items);
//    }
//
//    /**
//     * [EN] Input: Empty list of ChangeRequestRoleModel.
//     * [EN] Expected: Method should return without any exception and no modification to the empty list.
//     */
//    @Test
//    void groupAndSortCabUserGroups2_emptyListTest() {
//        // Arrange
//        List<ChangeRequestRoleModel> items = new ArrayList<>();
//
//        // Act
//        utils.groupAndSortCabUserGroups2(items);
//
//        // Assert
//        assertEquals(0, items.size());
//    }
//
//    /**
//     * [EN] Input: A list with one ChangeRequestRoleModel, but cabUserGroups is null.
//     * [EN] Expected: Method should return without exception and set workflowUsers to empty list.
//     */
//    @Test
//    void groupAndSortCabUserGroups2_nullCabUserGroupsTest() {
//        // Arrange
//        ChangeRequestRoleModel item = ChangeRequestRoleModel.builder().cabUserGroups(null).build();
//        List<ChangeRequestRoleModel> items = new ArrayList<>();
//        items.add(item);
//
//        // Act
//        utils.groupAndSortCabUserGroups2(items);
//
//        // Assert
//        assertNull(item.getCabUserGroups());
//        assertEquals(0, item.getWorkflowUsers().size());
//    }
//
//    /**
//     * [EN] Input: A list with one ChangeRequestRoleModel, but cabUserGroups is empty.
//     * [EN] Expected: Method should return without exception and set workflowUsers to empty list.
//     */
//    @Test
//    void groupAndSortCabUserGroups2_emptyCabUserGroupsTest() {
//        // Arrange
//        ChangeRequestRoleModel item =
//                ChangeRequestRoleModel.builder().cabUserGroups(new ArrayList<>()).build();
//        List<ChangeRequestRoleModel> items = new ArrayList<>();
//        items.add(item);
//
//        // Act
//        utils.groupAndSortCabUserGroups2(items);
//
//        // Assert
//        assertEquals(0, item.getCabUserGroups().size());
//        assertEquals(0, item.getWorkflowUsers().size());
//    }
//
//    /**
//     * [EN] Input: A list with one ChangeRequestRoleModel, with cabUserGroups having users with null changeRequestWorkflow id.
//     * [EN] Expected: Method should group by workflow and then by cabGroup, sort by cabGroupOrder.
//     */
//    @Test
//    void groupAndSortCabUserGroups2_nullWorkflowIdTest() {
//        // Arrange
//        Long workflow = null;
//        ChangeRequestRoleUserModel user1 =
//                ChangeRequestRoleUserModel.builder().username("user1").cabGroup(1).cabGroupOrder(1)
//                        .changeRequestWorkflowId(workflow).build();
//        ChangeRequestRoleUserModel user2 =
//                ChangeRequestRoleUserModel.builder().username("user2").cabGroup(2).cabGroupOrder(1)
//                        .changeRequestWorkflowId(workflow).build();
//        List<ChangeRequestRoleUserModel> cabUsers = new ArrayList<>();
//        cabUsers.add(user1);
//        cabUsers.add(user2);
//        ChangeRequestRoleModel item =
//                ChangeRequestRoleModel.builder().cabUserGroups(cabUsers).build();
//        List<ChangeRequestRoleModel> items = new ArrayList<>();
//        items.add(item);
//
//        // Act
//        utils.groupAndSortCabUserGroups2(items);
//
//        // Assert
//        assertEquals(1, item.getWorkflowUsers().size());
//        assertEquals(2, item.getWorkflowUsers().get(0).getWorkflows().size());
//        assertEquals("user1", item.getWorkflowUsers().get(0).getWorkflows().get(0).getUsers().get(0)
//                .getUsername());
//        assertEquals("user2", item.getWorkflowUsers().get(0).getWorkflows().get(1).getUsers().get(0)
//                .getUsername());
//    }
//
//    /**
//     * [EN] Input: A list with one ChangeRequestRoleModel, with cabUserGroups having users with different workflow and cabGroup.
//     * [EN] Expected: Method should group by workflow and then by cabGroup, sort by cabGroupOrder.
//     */
//    @Test
//    void groupAndSortCabUserGroups2_positiveTest() {
//        // Arrange
//        var workflow1 = 1L;
//        var workflow2 = 2L;
//        ChangeRequestRoleUserModel user1 =
//                ChangeRequestRoleUserModel.builder().username("user1").cabGroup(1).cabGroupOrder(1)
//                        .changeRequestWorkflowId(workflow1).build();
//        ChangeRequestRoleUserModel user2 =
//                ChangeRequestRoleUserModel.builder().username("user2").cabGroup(2).cabGroupOrder(1)
//                        .changeRequestWorkflowId(workflow1).build();
//        ChangeRequestRoleUserModel user3 =
//                ChangeRequestRoleUserModel.builder().username("user3").cabGroup(1).cabGroupOrder(1)
//                        .changeRequestWorkflowId(workflow2).build();
//        List<ChangeRequestRoleUserModel> cabUsers = new ArrayList<>();
//        cabUsers.add(user1);
//        cabUsers.add(user2);
//        cabUsers.add(user3);
//        ChangeRequestRoleModel item =
//                ChangeRequestRoleModel.builder().cabUserGroups(cabUsers).build();
//        List<ChangeRequestRoleModel> items = new ArrayList<>();
//        items.add(item);
//
//        // Act
//        utils.groupAndSortCabUserGroups2(items);
//
//        // Assert
//        assertEquals(2, item.getWorkflowUsers().size());
//        assertEquals(2, item.getWorkflowUsers().get(0).getWorkflows().size());
//        assertEquals(1, item.getWorkflowUsers().get(1).getWorkflows().size());
//    }
//
//    /**
//     * [EN] Input: A list with one ChangeRequestRoleModel, with cabUserGroups having users with null cabGroup.
//     * [EN] Expected: Method should group by workflow and then filter out users with null cabGroup.
//     */
//    @Test
//    void groupAndSortCabUserGroups2_nullCabGroupTest() {
//        // Arrange
//        var workflow1 = 1L;
//        ChangeRequestRoleUserModel user1 =
//                ChangeRequestRoleUserModel.builder().username("user1").cabGroup(null)
//                        .cabGroupOrder(1).changeRequestWorkflowId(workflow1).build();
//        ChangeRequestRoleUserModel user2 =
//                ChangeRequestRoleUserModel.builder().username("user2").cabGroup(1).cabGroupOrder(1)
//                        .changeRequestWorkflowId(workflow1).build();
//        List<ChangeRequestRoleUserModel> cabUsers = new ArrayList<>();
//        cabUsers.add(user1);
//        cabUsers.add(user2);
//        ChangeRequestRoleModel item =
//                ChangeRequestRoleModel.builder().cabUserGroups(cabUsers).build();
//        List<ChangeRequestRoleModel> items = new ArrayList<>();
//        items.add(item);
//
//        // Act
//        utils.groupAndSortCabUserGroups2(items);
//
//        // Assert
//        assertEquals(1, item.getWorkflowUsers().size());
//        assertEquals(1, item.getWorkflowUsers().get(0).getWorkflows().size());
//        assertEquals("user2", item.getWorkflowUsers().get(0).getWorkflows().get(0).getUsers().get(0)
//                .getUsername());
//    }
//
//    /**
//     * [EN] Input: A list with one ChangeRequestRoleModel, with cabUserGroups having users with null cabGroupOrder.
//     * [EN] Expected: Method should group by workflow and then by cabGroup, sort by cabGroupOrder with nulls last.
//     */
//    @Test
//    void groupAndSortCabUserGroups2_nullCabGroupOrderTest() {
//        // Arrange
//        var workflow1 = 1L;
//        ChangeRequestRoleUserModel user1 =
//                ChangeRequestRoleUserModel.builder().username("user1").cabGroup(1)
//                        .cabGroupOrder(null).changeRequestWorkflowId(workflow1).build();
//        ChangeRequestRoleUserModel user2 =
//                ChangeRequestRoleUserModel.builder().username("user2").cabGroup(1).cabGroupOrder(1)
//                        .changeRequestWorkflowId(workflow1).build();
//        List<ChangeRequestRoleUserModel> cabUsers = new ArrayList<>();
//        cabUsers.add(user1);
//        cabUsers.add(user2);
//        ChangeRequestRoleModel item =
//                ChangeRequestRoleModel.builder().cabUserGroups(cabUsers).build();
//        List<ChangeRequestRoleModel> items = new ArrayList<>();
//        items.add(item);
//
//        // Act
//        utils.groupAndSortCabUserGroups2(items);
//
//        // Assert
//        assertEquals(1, item.getWorkflowUsers().size());
//        assertEquals(1, item.getWorkflowUsers().get(0).getWorkflows().size());
//        assertEquals(2, item.getWorkflowUsers().get(0).getWorkflows().get(0).getUsers().size());
//        assertEquals("user2", item.getWorkflowUsers().get(0).getWorkflows().get(0).getUsers().get(0)
//                .getUsername());
//        assertEquals("user1", item.getWorkflowUsers().get(0).getWorkflows().get(0).getUsers().get(1)
//                .getUsername());
//    }
//}