package com.example.model;
import com.example.demo.model.ChangeRequestRoleModel;
import com.example.demo.model.ChangeRequestRoleUserModel;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.MockitoAnnotations;
import java.util.*;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
/**
 * Generated by K-tool
 * Created date: 2025-06-10
 */
public class UtilsTest {
    private Utils utils;
    @BeforeEach
    void setUp() {
        MockitoAnnotations.openMocks(this);
        utils = new Utils();
    }
    /**
     * [EN] Input: A list of ChangeRequestRoleModel with cabUserGroups having multiple users in different groups with varying cabGroupOrder.
     * [EN] Expected: The cabUserGroups should be grouped by cabGroup, and within each group, users should be sorted by cabGroupOrder. The groupedCabUserGroups should be set correctly.
     */
    @Test
    void groupAndSortCabUserGroups_positiveTest() {
        // Arrange
        ChangeRequestRoleModel item1 = new ChangeRequestRoleModel();
        List<ChangeRequestRoleUserModel> cabUsers1 = new ArrayList<>();
        cabUsers1.add(ChangeRequestRoleUserModel.builder().cabGroup(2).cabGroupOrder(2).build());
        cabUsers1.add(ChangeRequestRoleUserModel.builder().cabGroup(1).cabGroupOrder(1).build());
        cabUsers1.add(ChangeRequestRoleUserModel.builder().cabGroup(2).cabGroupOrder(1).build());
        item1.setCabUserGroups(cabUsers1);
        ChangeRequestRoleModel item2 = new ChangeRequestRoleModel();
        List<ChangeRequestRoleUserModel> cabUsers2 = new ArrayList<>();
        cabUsers2.add(ChangeRequestRoleUserModel.builder().cabGroup(1).cabGroupOrder(2).build());
        cabUsers2.add(ChangeRequestRoleUserModel.builder().cabGroup(1).cabGroupOrder(1).build());
        item2.setCabUserGroups(cabUsers2);
        List<ChangeRequestRoleModel> items = Arrays.asList(item1, item2);
        // Act
        utils.groupAndSortCabUserGroups(items);
        // Assert
        List<List<ChangeRequestRoleUserModel>> grouped1 = item1.getGroupedCabUserGroups();

        assertEquals(2, grouped1.size());
        assertEquals(1, grouped1.get(0).get(0).getCabGroup());
        assertEquals(2, grouped1.get(1).get(0).getCabGroup());
        assertEquals(1, grouped1.get(1).get(0).getCabGroupOrder());
        assertEquals(2, grouped1.get(1).get(1).getCabGroupOrder());
        List<List<ChangeRequestRoleUserModel>> grouped2 = item2.getGroupedCabUserGroups();
        assertEquals(1, grouped2.size());
        assertEquals(1, grouped2.get(0).get(0).getCabGroupOrder());
        assertEquals(2, grouped2.get(0).get(1).getCabGroupOrder());
    }
    /**
     * [EN] Input: A list of ChangeRequestRoleModel with some items having null cabUserGroups.
     * [EN] Expected: The method should handle null cabUserGroups gracefully, and the groupedCabUserGroups should be null for those items.
     */
    @Test
    void groupAndSortCabUserGroups_nullCabUserGroupsTest() {
        // Arrange
        ChangeRequestRoleModel item1 = new ChangeRequestRoleModel();
        item1.setCabUserGroups(null);
        ChangeRequestRoleModel item2 = new ChangeRequestRoleModel();
        List<ChangeRequestRoleUserModel> cabUsers = new ArrayList<>();
        cabUsers.add(ChangeRequestRoleUserModel.builder().cabGroup(1).cabGroupOrder(1).build());
        item2.setCabUserGroups(cabUsers);
        List<ChangeRequestRoleModel> items = Arrays.asList(item1, item2);
        // Act
        utils.groupAndSortCabUserGroups(items);
        // Assert
        assertNull(item1.getGroupedCabUserGroups());
        assertEquals(1, item2.getGroupedCabUserGroups().size());
    }
    /**
     * [EN] Input: A list of ChangeRequestRoleModel with cabUserGroups having null cabGroup and cabGroupOrder values.
     * [EN] Expected: The method should handle null cabGroup and cabGroupOrder values gracefully, sorting them to the end.
     */
    @Test
    void groupAndSortCabUserGroups_nullCabGroupAndOrderTest() {
        // Arrange
        ChangeRequestRoleModel item1 = new ChangeRequestRoleModel();
        List<ChangeRequestRoleUserModel> cabUsers1 = new ArrayList<>();
        cabUsers1.add(ChangeRequestRoleUserModel.builder().cabGroup(1).cabGroupOrder(1).build());
        cabUsers1.add(ChangeRequestRoleUserModel.builder().cabGroup(null).cabGroupOrder(null).build());
        item1.setCabUserGroups(cabUsers1);
        List<ChangeRequestRoleModel> items = Collections.singletonList(item1);
        // Act
        utils.groupAndSortCabUserGroups(items);
        // Assert
        List<List<ChangeRequestRoleUserModel>> grouped1 = item1.getGroupedCabUserGroups();
        assertEquals(2, grouped1.get(0).size());
        assertEquals(1, grouped1.size());
        assertEquals(1, grouped1.get(0).get(0).getCabGroup());
        assertNull(grouped1.get(0).get(1).getCabGroup());
    }
    /**
     * [EN] Input: A list of ChangeRequestRoleModel with empty cabUserGroups.
     * [EN] Expected: The method should handle empty cabUserGroups gracefully, resulting in an empty groupedCabUserGroups.
     */
    @Test
    void groupAndSortCabUserGroups_emptyCabUserGroupsTest() {
        // Arrange
        ChangeRequestRoleModel item1 = new ChangeRequestRoleModel();
        item1.setCabUserGroups(new ArrayList<>());
        List<ChangeRequestRoleModel> items = Collections.singletonList(item1);
        // Act
        utils.groupAndSortCabUserGroups(items);
        // Assert
        assertEquals(0, item1.getGroupedCabUserGroups().size());
    }
    /**
     * [EN] Input: A list of ChangeRequestRoleModel with a single ChangeRequestRoleModel having a single ChangeRequestRoleUserModel in its cabUserGroups.
     * [EN] Expected: The groupedCabUserGroups should contain a single list with the single ChangeRequestRoleUserModel.
     */
    @Test
    void groupAndSortCabUserGroups_singleUserTest() {
        // Arrange
        ChangeRequestRoleModel item1 = new ChangeRequestRoleModel();
        List<ChangeRequestRoleUserModel> cabUsers1 = new ArrayList<>();
        cabUsers1.add(ChangeRequestRoleUserModel.builder().cabGroup(1).cabGroupOrder(1).build());
        item1.setCabUserGroups(cabUsers1);
        List<ChangeRequestRoleModel> items = Collections.singletonList(item1);
        // Act
        utils.groupAndSortCabUserGroups(items);
        // Assert
        List<List<ChangeRequestRoleUserModel>> grouped1 = item1.getGroupedCabUserGroups();
        assertEquals(1, grouped1.size());
        assertEquals(1, grouped1.get(0).size());
        assertEquals(1, grouped1.get(0).get(0).getCabGroup());
        assertEquals(1, grouped1.get(0).get(0).getCabGroupOrder());
    }

    /**
     * [EN] Input: A null list of ChangeRequestRoleModel.
     * [EN] Expected: The method should handle null input gracefully without throwing an exception.
     */
    @Test
    void groupAndSortCabUserGroups_nullInputTest() {
        // Arrange
        List<ChangeRequestRoleModel> items = null;

        // Act & Assert
        // This should not throw an exception
        utils.groupAndSortCabUserGroups(items);
    }
}
